/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InvoiceElementStatusSyncOpenModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvoiceElementStatusSyncOpenModel{}

// InvoiceElementStatusSyncOpenModel struct for InvoiceElementStatusSyncOpenModel
type InvoiceElementStatusSyncOpenModel struct {
	// 同步申请id，每次发起同步时生成，isv每次请求需要保证唯一
	ApplyId *string `json:"apply_id,omitempty"`
	// 报销详情地址，提供用户通过发票管家查看报销进度的地址  如果报销企业入驻发票管家时需要isv传入报销详情地址，则必须提供
	ExpenseDetailUrl *string `json:"expense_detail_url,omitempty"`
	// 发票代码
	InvoiceCode *string `json:"invoice_code,omitempty"`
	// 发票号码
	InvoiceNo *string `json:"invoice_no,omitempty"`
}

// NewInvoiceElementStatusSyncOpenModel instantiates a new InvoiceElementStatusSyncOpenModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceElementStatusSyncOpenModel() *InvoiceElementStatusSyncOpenModel {
	this := InvoiceElementStatusSyncOpenModel{}
	return &this
}

// NewInvoiceElementStatusSyncOpenModelWithDefaults instantiates a new InvoiceElementStatusSyncOpenModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceElementStatusSyncOpenModelWithDefaults() *InvoiceElementStatusSyncOpenModel {
	this := InvoiceElementStatusSyncOpenModel{}
	return &this
}

// GetApplyId returns the ApplyId field value if set, zero value otherwise.
func (o *InvoiceElementStatusSyncOpenModel) GetApplyId() string {
	if o == nil || IsNil(o.ApplyId) {
		var ret string
		return ret
	}
	return *o.ApplyId
}

// GetApplyIdOk returns a tuple with the ApplyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceElementStatusSyncOpenModel) GetApplyIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApplyId) {
		return nil, false
	}
	return o.ApplyId, true
}

// HasApplyId returns a boolean if a field has been set.
func (o *InvoiceElementStatusSyncOpenModel) HasApplyId() bool {
	if o != nil && !IsNil(o.ApplyId) {
		return true
	}

	return false
}

// SetApplyId gets a reference to the given string and assigns it to the ApplyId field.
func (o *InvoiceElementStatusSyncOpenModel) SetApplyId(v string) {
	o.ApplyId = &v
}

// GetExpenseDetailUrl returns the ExpenseDetailUrl field value if set, zero value otherwise.
func (o *InvoiceElementStatusSyncOpenModel) GetExpenseDetailUrl() string {
	if o == nil || IsNil(o.ExpenseDetailUrl) {
		var ret string
		return ret
	}
	return *o.ExpenseDetailUrl
}

// GetExpenseDetailUrlOk returns a tuple with the ExpenseDetailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceElementStatusSyncOpenModel) GetExpenseDetailUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ExpenseDetailUrl) {
		return nil, false
	}
	return o.ExpenseDetailUrl, true
}

// HasExpenseDetailUrl returns a boolean if a field has been set.
func (o *InvoiceElementStatusSyncOpenModel) HasExpenseDetailUrl() bool {
	if o != nil && !IsNil(o.ExpenseDetailUrl) {
		return true
	}

	return false
}

// SetExpenseDetailUrl gets a reference to the given string and assigns it to the ExpenseDetailUrl field.
func (o *InvoiceElementStatusSyncOpenModel) SetExpenseDetailUrl(v string) {
	o.ExpenseDetailUrl = &v
}

// GetInvoiceCode returns the InvoiceCode field value if set, zero value otherwise.
func (o *InvoiceElementStatusSyncOpenModel) GetInvoiceCode() string {
	if o == nil || IsNil(o.InvoiceCode) {
		var ret string
		return ret
	}
	return *o.InvoiceCode
}

// GetInvoiceCodeOk returns a tuple with the InvoiceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceElementStatusSyncOpenModel) GetInvoiceCodeOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceCode) {
		return nil, false
	}
	return o.InvoiceCode, true
}

// HasInvoiceCode returns a boolean if a field has been set.
func (o *InvoiceElementStatusSyncOpenModel) HasInvoiceCode() bool {
	if o != nil && !IsNil(o.InvoiceCode) {
		return true
	}

	return false
}

// SetInvoiceCode gets a reference to the given string and assigns it to the InvoiceCode field.
func (o *InvoiceElementStatusSyncOpenModel) SetInvoiceCode(v string) {
	o.InvoiceCode = &v
}

// GetInvoiceNo returns the InvoiceNo field value if set, zero value otherwise.
func (o *InvoiceElementStatusSyncOpenModel) GetInvoiceNo() string {
	if o == nil || IsNil(o.InvoiceNo) {
		var ret string
		return ret
	}
	return *o.InvoiceNo
}

// GetInvoiceNoOk returns a tuple with the InvoiceNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InvoiceElementStatusSyncOpenModel) GetInvoiceNoOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceNo) {
		return nil, false
	}
	return o.InvoiceNo, true
}

// HasInvoiceNo returns a boolean if a field has been set.
func (o *InvoiceElementStatusSyncOpenModel) HasInvoiceNo() bool {
	if o != nil && !IsNil(o.InvoiceNo) {
		return true
	}

	return false
}

// SetInvoiceNo gets a reference to the given string and assigns it to the InvoiceNo field.
func (o *InvoiceElementStatusSyncOpenModel) SetInvoiceNo(v string) {
	o.InvoiceNo = &v
}

func (o InvoiceElementStatusSyncOpenModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvoiceElementStatusSyncOpenModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplyId) {
		toSerialize["apply_id"] = o.ApplyId
	}
	if !IsNil(o.ExpenseDetailUrl) {
		toSerialize["expense_detail_url"] = o.ExpenseDetailUrl
	}
	if !IsNil(o.InvoiceCode) {
		toSerialize["invoice_code"] = o.InvoiceCode
	}
	if !IsNil(o.InvoiceNo) {
		toSerialize["invoice_no"] = o.InvoiceNo
	}
	return toSerialize, nil
}

type NullableInvoiceElementStatusSyncOpenModel struct {
	value *InvoiceElementStatusSyncOpenModel
	isSet bool
}

func (v NullableInvoiceElementStatusSyncOpenModel) Get() *InvoiceElementStatusSyncOpenModel {
	return v.value
}

func (v *NullableInvoiceElementStatusSyncOpenModel) Set(val *InvoiceElementStatusSyncOpenModel) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceElementStatusSyncOpenModel) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceElementStatusSyncOpenModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceElementStatusSyncOpenModel(val *InvoiceElementStatusSyncOpenModel) *NullableInvoiceElementStatusSyncOpenModel {
	return &NullableInvoiceElementStatusSyncOpenModel{value: val, isSet: true}
}

func (v NullableInvoiceElementStatusSyncOpenModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceElementStatusSyncOpenModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


