/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayEcoMycarParkingConfigQueryDefaultResponse struct for AlipayEcoMycarParkingConfigQueryDefaultResponse
type AlipayEcoMycarParkingConfigQueryDefaultResponse struct {
	AlipayEcoMycarParkingConfigQueryErrorResponseModel *AlipayEcoMycarParkingConfigQueryErrorResponseModel
	CommonErrorType                                    *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayEcoMycarParkingConfigQueryDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayEcoMycarParkingConfigQueryErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayEcoMycarParkingConfigQueryErrorResponseModel)
	if err == nil {
		jsonAlipayEcoMycarParkingConfigQueryErrorResponseModel, _ := json.Marshal(dst.AlipayEcoMycarParkingConfigQueryErrorResponseModel)
		if string(jsonAlipayEcoMycarParkingConfigQueryErrorResponseModel) == "{}" { // empty struct
			dst.AlipayEcoMycarParkingConfigQueryErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayEcoMycarParkingConfigQueryErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayEcoMycarParkingConfigQueryErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayEcoMycarParkingConfigQueryDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayEcoMycarParkingConfigQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayEcoMycarParkingConfigQueryErrorResponseModel != nil {
		return json.Marshal(&src.AlipayEcoMycarParkingConfigQueryErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayEcoMycarParkingConfigQueryDefaultResponse struct {
	value *AlipayEcoMycarParkingConfigQueryDefaultResponse
	isSet bool
}

func (v NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) Get() *AlipayEcoMycarParkingConfigQueryDefaultResponse {
	return v.value
}

func (v *NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) Set(val *AlipayEcoMycarParkingConfigQueryDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayEcoMycarParkingConfigQueryDefaultResponse(val *AlipayEcoMycarParkingConfigQueryDefaultResponse) *NullableAlipayEcoMycarParkingConfigQueryDefaultResponse {
	return &NullableAlipayEcoMycarParkingConfigQueryDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayEcoMycarParkingConfigQueryDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
