/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayIserviceCcmSwLibraryDeleteDefaultResponse struct for AlipayIserviceCcmSwLibraryDeleteDefaultResponse
type AlipayIserviceCcmSwLibraryDeleteDefaultResponse struct {
	AlipayIserviceCcmSwLibraryDeleteErrorResponseModel *AlipayIserviceCcmSwLibraryDeleteErrorResponseModel
	CommonErrorType                                    *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayIserviceCcmSwLibraryDeleteDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayIserviceCcmSwLibraryDeleteErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel)
	if err == nil {
		jsonAlipayIserviceCcmSwLibraryDeleteErrorResponseModel, _ := json.Marshal(dst.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel)
		if string(jsonAlipayIserviceCcmSwLibraryDeleteErrorResponseModel) == "{}" { // empty struct
			dst.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayIserviceCcmSwLibraryDeleteDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayIserviceCcmSwLibraryDeleteDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel != nil {
		return json.Marshal(&src.AlipayIserviceCcmSwLibraryDeleteErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse struct {
	value *AlipayIserviceCcmSwLibraryDeleteDefaultResponse
	isSet bool
}

func (v NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) Get() *AlipayIserviceCcmSwLibraryDeleteDefaultResponse {
	return v.value
}

func (v *NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) Set(val *AlipayIserviceCcmSwLibraryDeleteDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse(val *AlipayIserviceCcmSwLibraryDeleteDefaultResponse) *NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse {
	return &NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayIserviceCcmSwLibraryDeleteDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
