/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse struct for AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse
type AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse struct {
	AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel *AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel
	CommonErrorType                                                     *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel)
	if err == nil {
		jsonAlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel, _ := json.Marshal(dst.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel)
		if string(jsonAlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel) == "{}" { // empty struct
			dst.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel != nil {
		return json.Marshal(&src.AlipayOpenServicemarketPromotiontaskRelationQueryErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse struct {
	value *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse
	isSet bool
}

func (v NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) Get() *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse {
	return v.value
}

func (v *NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) Set(val *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse(val *AlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) *NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse {
	return &NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenServicemarketPromotiontaskRelationQueryDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
