/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayOpenPublicAdvertCreateDefaultResponse struct for AlipayOpenPublicAdvertCreateDefaultResponse
type AlipayOpenPublicAdvertCreateDefaultResponse struct {
	AlipayOpenPublicAdvertCreateErrorResponseModel *AlipayOpenPublicAdvertCreateErrorResponseModel
	CommonErrorType                                *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayOpenPublicAdvertCreateDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayOpenPublicAdvertCreateErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayOpenPublicAdvertCreateErrorResponseModel)
	if err == nil {
		jsonAlipayOpenPublicAdvertCreateErrorResponseModel, _ := json.Marshal(dst.AlipayOpenPublicAdvertCreateErrorResponseModel)
		if string(jsonAlipayOpenPublicAdvertCreateErrorResponseModel) == "{}" { // empty struct
			dst.AlipayOpenPublicAdvertCreateErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayOpenPublicAdvertCreateErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayOpenPublicAdvertCreateErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayOpenPublicAdvertCreateDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayOpenPublicAdvertCreateDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayOpenPublicAdvertCreateErrorResponseModel != nil {
		return json.Marshal(&src.AlipayOpenPublicAdvertCreateErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayOpenPublicAdvertCreateDefaultResponse struct {
	value *AlipayOpenPublicAdvertCreateDefaultResponse
	isSet bool
}

func (v NullableAlipayOpenPublicAdvertCreateDefaultResponse) Get() *AlipayOpenPublicAdvertCreateDefaultResponse {
	return v.value
}

func (v *NullableAlipayOpenPublicAdvertCreateDefaultResponse) Set(val *AlipayOpenPublicAdvertCreateDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenPublicAdvertCreateDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenPublicAdvertCreateDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenPublicAdvertCreateDefaultResponse(val *AlipayOpenPublicAdvertCreateDefaultResponse) *NullableAlipayOpenPublicAdvertCreateDefaultResponse {
	return &NullableAlipayOpenPublicAdvertCreateDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayOpenPublicAdvertCreateDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenPublicAdvertCreateDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
