/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the AlipaySecurityDataSssCreateModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipaySecurityDataSssCreateModel{}

// AlipaySecurityDataSssCreateModel struct for AlipaySecurityDataSssCreateModel
type AlipaySecurityDataSssCreateModel struct {
	// body,可选，无openid，有枚举值，注意事项
	AreaCode *string                `json:"area_code,omitempty"`
	F        *JinyoutestopenidThree `json:"f,omitempty"`
}

// NewAlipaySecurityDataSssCreateModel instantiates a new AlipaySecurityDataSssCreateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipaySecurityDataSssCreateModel() *AlipaySecurityDataSssCreateModel {
	this := AlipaySecurityDataSssCreateModel{}
	return &this
}

// NewAlipaySecurityDataSssCreateModelWithDefaults instantiates a new AlipaySecurityDataSssCreateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipaySecurityDataSssCreateModelWithDefaults() *AlipaySecurityDataSssCreateModel {
	this := AlipaySecurityDataSssCreateModel{}
	return &this
}

// GetAreaCode returns the AreaCode field value if set, zero value otherwise.
func (o *AlipaySecurityDataSssCreateModel) GetAreaCode() string {
	if o == nil || IsNil(o.AreaCode) {
		var ret string
		return ret
	}
	return *o.AreaCode
}

// GetAreaCodeOk returns a tuple with the AreaCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipaySecurityDataSssCreateModel) GetAreaCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AreaCode) {
		return nil, false
	}
	return o.AreaCode, true
}

// HasAreaCode returns a boolean if a field has been set.
func (o *AlipaySecurityDataSssCreateModel) HasAreaCode() bool {
	if o != nil && !IsNil(o.AreaCode) {
		return true
	}

	return false
}

// SetAreaCode gets a reference to the given string and assigns it to the AreaCode field.
func (o *AlipaySecurityDataSssCreateModel) SetAreaCode(v string) {
	o.AreaCode = &v
}

// GetF returns the F field value if set, zero value otherwise.
func (o *AlipaySecurityDataSssCreateModel) GetF() JinyoutestopenidThree {
	if o == nil || IsNil(o.F) {
		var ret JinyoutestopenidThree
		return ret
	}
	return *o.F
}

// GetFOk returns a tuple with the F field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipaySecurityDataSssCreateModel) GetFOk() (*JinyoutestopenidThree, bool) {
	if o == nil || IsNil(o.F) {
		return nil, false
	}
	return o.F, true
}

// HasF returns a boolean if a field has been set.
func (o *AlipaySecurityDataSssCreateModel) HasF() bool {
	if o != nil && !IsNil(o.F) {
		return true
	}

	return false
}

// SetF gets a reference to the given JinyoutestopenidThree and assigns it to the F field.
func (o *AlipaySecurityDataSssCreateModel) SetF(v JinyoutestopenidThree) {
	o.F = &v
}

func (o AlipaySecurityDataSssCreateModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipaySecurityDataSssCreateModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AreaCode) {
		toSerialize["area_code"] = o.AreaCode
	}
	if !IsNil(o.F) {
		toSerialize["f"] = o.F
	}
	return toSerialize, nil
}

type NullableAlipaySecurityDataSssCreateModel struct {
	value *AlipaySecurityDataSssCreateModel
	isSet bool
}

func (v NullableAlipaySecurityDataSssCreateModel) Get() *AlipaySecurityDataSssCreateModel {
	return v.value
}

func (v *NullableAlipaySecurityDataSssCreateModel) Set(val *AlipaySecurityDataSssCreateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipaySecurityDataSssCreateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipaySecurityDataSssCreateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipaySecurityDataSssCreateModel(val *AlipaySecurityDataSssCreateModel) *NullableAlipaySecurityDataSssCreateModel {
	return &NullableAlipaySecurityDataSssCreateModel{value: val, isSet: true}
}

func (v NullableAlipaySecurityDataSssCreateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipaySecurityDataSssCreateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
