/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuthFieldSceneDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthFieldSceneDTO{}

// AuthFieldSceneDTO struct for AuthFieldSceneDTO
type AuthFieldSceneDTO struct {
	// 场景CODE
	SceneCode *string `json:"scene_code,omitempty"`
	// 场景code描述
	SceneDesc *string `json:"scene_desc,omitempty"`
}

// NewAuthFieldSceneDTO instantiates a new AuthFieldSceneDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthFieldSceneDTO() *AuthFieldSceneDTO {
	this := AuthFieldSceneDTO{}
	return &this
}

// NewAuthFieldSceneDTOWithDefaults instantiates a new AuthFieldSceneDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthFieldSceneDTOWithDefaults() *AuthFieldSceneDTO {
	this := AuthFieldSceneDTO{}
	return &this
}

// GetSceneCode returns the SceneCode field value if set, zero value otherwise.
func (o *AuthFieldSceneDTO) GetSceneCode() string {
	if o == nil || IsNil(o.SceneCode) {
		var ret string
		return ret
	}
	return *o.SceneCode
}

// GetSceneCodeOk returns a tuple with the SceneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthFieldSceneDTO) GetSceneCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SceneCode) {
		return nil, false
	}
	return o.SceneCode, true
}

// HasSceneCode returns a boolean if a field has been set.
func (o *AuthFieldSceneDTO) HasSceneCode() bool {
	if o != nil && !IsNil(o.SceneCode) {
		return true
	}

	return false
}

// SetSceneCode gets a reference to the given string and assigns it to the SceneCode field.
func (o *AuthFieldSceneDTO) SetSceneCode(v string) {
	o.SceneCode = &v
}

// GetSceneDesc returns the SceneDesc field value if set, zero value otherwise.
func (o *AuthFieldSceneDTO) GetSceneDesc() string {
	if o == nil || IsNil(o.SceneDesc) {
		var ret string
		return ret
	}
	return *o.SceneDesc
}

// GetSceneDescOk returns a tuple with the SceneDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthFieldSceneDTO) GetSceneDescOk() (*string, bool) {
	if o == nil || IsNil(o.SceneDesc) {
		return nil, false
	}
	return o.SceneDesc, true
}

// HasSceneDesc returns a boolean if a field has been set.
func (o *AuthFieldSceneDTO) HasSceneDesc() bool {
	if o != nil && !IsNil(o.SceneDesc) {
		return true
	}

	return false
}

// SetSceneDesc gets a reference to the given string and assigns it to the SceneDesc field.
func (o *AuthFieldSceneDTO) SetSceneDesc(v string) {
	o.SceneDesc = &v
}

func (o AuthFieldSceneDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthFieldSceneDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SceneCode) {
		toSerialize["scene_code"] = o.SceneCode
	}
	if !IsNil(o.SceneDesc) {
		toSerialize["scene_desc"] = o.SceneDesc
	}
	return toSerialize, nil
}

type NullableAuthFieldSceneDTO struct {
	value *AuthFieldSceneDTO
	isSet bool
}

func (v NullableAuthFieldSceneDTO) Get() *AuthFieldSceneDTO {
	return v.value
}

func (v *NullableAuthFieldSceneDTO) Set(val *AuthFieldSceneDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthFieldSceneDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthFieldSceneDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthFieldSceneDTO(val *AuthFieldSceneDTO) *NullableAuthFieldSceneDTO {
	return &NullableAuthFieldSceneDTO{value: val, isSet: true}
}

func (v NullableAuthFieldSceneDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthFieldSceneDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


