/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// AlipayEbppPdeductSignValidateDefaultResponse struct for AlipayEbppPdeductSignValidateDefaultResponse
type AlipayEbppPdeductSignValidateDefaultResponse struct {
	AlipayEbppPdeductSignValidateErrorResponseModel *AlipayEbppPdeductSignValidateErrorResponseModel
	CommonErrorType *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayEbppPdeductSignValidateDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayEbppPdeductSignValidateErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayEbppPdeductSignValidateErrorResponseModel);
	if err == nil {
		jsonAlipayEbppPdeductSignValidateErrorResponseModel, _ := json.Marshal(dst.AlipayEbppPdeductSignValidateErrorResponseModel)
		if string(jsonAlipayEbppPdeductSignValidateErrorResponseModel) == "{}" { // empty struct
			dst.AlipayEbppPdeductSignValidateErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayEbppPdeductSignValidateErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayEbppPdeductSignValidateErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType);
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayEbppPdeductSignValidateDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayEbppPdeductSignValidateDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayEbppPdeductSignValidateErrorResponseModel != nil {
		return json.Marshal(&src.AlipayEbppPdeductSignValidateErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableAlipayEbppPdeductSignValidateDefaultResponse struct {
	value *AlipayEbppPdeductSignValidateDefaultResponse
	isSet bool
}

func (v NullableAlipayEbppPdeductSignValidateDefaultResponse) Get() *AlipayEbppPdeductSignValidateDefaultResponse {
	return v.value
}

func (v *NullableAlipayEbppPdeductSignValidateDefaultResponse) Set(val *AlipayEbppPdeductSignValidateDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayEbppPdeductSignValidateDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayEbppPdeductSignValidateDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayEbppPdeductSignValidateDefaultResponse(val *AlipayEbppPdeductSignValidateDefaultResponse) *NullableAlipayEbppPdeductSignValidateDefaultResponse {
	return &NullableAlipayEbppPdeductSignValidateDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayEbppPdeductSignValidateDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayEbppPdeductSignValidateDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


