/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// AlipayCommerceEcEmployeeIdlistQueryDefaultResponse struct for AlipayCommerceEcEmployeeIdlistQueryDefaultResponse
type AlipayCommerceEcEmployeeIdlistQueryDefaultResponse struct {
	AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel *AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel
	CommonErrorType *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel);
	if err == nil {
		jsonAlipayCommerceEcEmployeeIdlistQueryErrorResponseModel, _ := json.Marshal(dst.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel)
		if string(jsonAlipayCommerceEcEmployeeIdlistQueryErrorResponseModel) == "{}" { // empty struct
			dst.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType);
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayCommerceEcEmployeeIdlistQueryDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel != nil {
		return json.Marshal(&src.AlipayCommerceEcEmployeeIdlistQueryErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse struct {
	value *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse
	isSet bool
}

func (v NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) Get() *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse {
	return v.value
}

func (v *NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) Set(val *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse(val *AlipayCommerceEcEmployeeIdlistQueryDefaultResponse) *NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse {
	return &NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayCommerceEcEmployeeIdlistQueryDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


