/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// AlipayOpenMiniInnerversionAuditCancelDefaultResponse struct for AlipayOpenMiniInnerversionAuditCancelDefaultResponse
type AlipayOpenMiniInnerversionAuditCancelDefaultResponse struct {
	AlipayOpenMiniInnerversionAuditCancelErrorResponseModel *AlipayOpenMiniInnerversionAuditCancelErrorResponseModel
	CommonErrorType *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayOpenMiniInnerversionAuditCancelDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayOpenMiniInnerversionAuditCancelErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel);
	if err == nil {
		jsonAlipayOpenMiniInnerversionAuditCancelErrorResponseModel, _ := json.Marshal(dst.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel)
		if string(jsonAlipayOpenMiniInnerversionAuditCancelErrorResponseModel) == "{}" { // empty struct
			dst.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType);
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayOpenMiniInnerversionAuditCancelDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayOpenMiniInnerversionAuditCancelDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel != nil {
		return json.Marshal(&src.AlipayOpenMiniInnerversionAuditCancelErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse struct {
	value *AlipayOpenMiniInnerversionAuditCancelDefaultResponse
	isSet bool
}

func (v NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) Get() *AlipayOpenMiniInnerversionAuditCancelDefaultResponse {
	return v.value
}

func (v *NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) Set(val *AlipayOpenMiniInnerversionAuditCancelDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse(val *AlipayOpenMiniInnerversionAuditCancelDefaultResponse) *NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse {
	return &NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenMiniInnerversionAuditCancelDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


