/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RecruitVoucher type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecruitVoucher{}

// RecruitVoucher struct for RecruitVoucher
type RecruitVoucher struct {
	// 券活动id。支持商家券（创建商家券请参考https://opendocs.alipay.com/apis/01xm17）和支付券（创建支付券请参考https://opendocs.alipay.com/pre-apis/027185，仅供受邀用户使用），取值均为返回结果的activity_id字段。
	ActivityId *string `json:"activity_id,omitempty"`
}

// NewRecruitVoucher instantiates a new RecruitVoucher object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecruitVoucher() *RecruitVoucher {
	this := RecruitVoucher{}
	return &this
}

// NewRecruitVoucherWithDefaults instantiates a new RecruitVoucher object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecruitVoucherWithDefaults() *RecruitVoucher {
	this := RecruitVoucher{}
	return &this
}

// GetActivityId returns the ActivityId field value if set, zero value otherwise.
func (o *RecruitVoucher) GetActivityId() string {
	if o == nil || IsNil(o.ActivityId) {
		var ret string
		return ret
	}
	return *o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecruitVoucher) GetActivityIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActivityId) {
		return nil, false
	}
	return o.ActivityId, true
}

// HasActivityId returns a boolean if a field has been set.
func (o *RecruitVoucher) HasActivityId() bool {
	if o != nil && !IsNil(o.ActivityId) {
		return true
	}

	return false
}

// SetActivityId gets a reference to the given string and assigns it to the ActivityId field.
func (o *RecruitVoucher) SetActivityId(v string) {
	o.ActivityId = &v
}

func (o RecruitVoucher) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecruitVoucher) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActivityId) {
		toSerialize["activity_id"] = o.ActivityId
	}
	return toSerialize, nil
}

type NullableRecruitVoucher struct {
	value *RecruitVoucher
	isSet bool
}

func (v NullableRecruitVoucher) Get() *RecruitVoucher {
	return v.value
}

func (v *NullableRecruitVoucher) Set(val *RecruitVoucher) {
	v.value = val
	v.isSet = true
}

func (v NullableRecruitVoucher) IsSet() bool {
	return v.isSet
}

func (v *NullableRecruitVoucher) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecruitVoucher(val *RecruitVoucher) *NullableRecruitVoucher {
	return &NullableRecruitVoucher{value: val, isSet: true}
}

func (v NullableRecruitVoucher) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecruitVoucher) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


