/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayOpenServicemarketOrderNotifyDefaultResponse struct for AlipayOpenServicemarketOrderNotifyDefaultResponse
type AlipayOpenServicemarketOrderNotifyDefaultResponse struct {
	AlipayOpenServicemarketOrderNotifyErrorResponseModel *AlipayOpenServicemarketOrderNotifyErrorResponseModel
	CommonErrorType                                      *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayOpenServicemarketOrderNotifyDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayOpenServicemarketOrderNotifyErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayOpenServicemarketOrderNotifyErrorResponseModel)
	if err == nil {
		jsonAlipayOpenServicemarketOrderNotifyErrorResponseModel, _ := json.Marshal(dst.AlipayOpenServicemarketOrderNotifyErrorResponseModel)
		if string(jsonAlipayOpenServicemarketOrderNotifyErrorResponseModel) == "{}" { // empty struct
			dst.AlipayOpenServicemarketOrderNotifyErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayOpenServicemarketOrderNotifyErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayOpenServicemarketOrderNotifyErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayOpenServicemarketOrderNotifyDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayOpenServicemarketOrderNotifyDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayOpenServicemarketOrderNotifyErrorResponseModel != nil {
		return json.Marshal(&src.AlipayOpenServicemarketOrderNotifyErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayOpenServicemarketOrderNotifyDefaultResponse struct {
	value *AlipayOpenServicemarketOrderNotifyDefaultResponse
	isSet bool
}

func (v NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) Get() *AlipayOpenServicemarketOrderNotifyDefaultResponse {
	return v.value
}

func (v *NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) Set(val *AlipayOpenServicemarketOrderNotifyDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenServicemarketOrderNotifyDefaultResponse(val *AlipayOpenServicemarketOrderNotifyDefaultResponse) *NullableAlipayOpenServicemarketOrderNotifyDefaultResponse {
	return &NullableAlipayOpenServicemarketOrderNotifyDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenServicemarketOrderNotifyDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
