/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// AlipayCommerceEcDepartmentInfoModifyDefaultResponse struct for AlipayCommerceEcDepartmentInfoModifyDefaultResponse
type AlipayCommerceEcDepartmentInfoModifyDefaultResponse struct {
	AlipayCommerceEcDepartmentInfoModifyErrorResponseModel *AlipayCommerceEcDepartmentInfoModifyErrorResponseModel
	CommonErrorType *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayCommerceEcDepartmentInfoModifyDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayCommerceEcDepartmentInfoModifyErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel);
	if err == nil {
		jsonAlipayCommerceEcDepartmentInfoModifyErrorResponseModel, _ := json.Marshal(dst.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel)
		if string(jsonAlipayCommerceEcDepartmentInfoModifyErrorResponseModel) == "{}" { // empty struct
			dst.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType);
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayCommerceEcDepartmentInfoModifyDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayCommerceEcDepartmentInfoModifyDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel != nil {
		return json.Marshal(&src.AlipayCommerceEcDepartmentInfoModifyErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse struct {
	value *AlipayCommerceEcDepartmentInfoModifyDefaultResponse
	isSet bool
}

func (v NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) Get() *AlipayCommerceEcDepartmentInfoModifyDefaultResponse {
	return v.value
}

func (v *NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) Set(val *AlipayCommerceEcDepartmentInfoModifyDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse(val *AlipayCommerceEcDepartmentInfoModifyDefaultResponse) *NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse {
	return &NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayCommerceEcDepartmentInfoModifyDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


