/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the AlipayOpenPublicMessageGroupSendModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayOpenPublicMessageGroupSendModel{}

// AlipayOpenPublicMessageGroupSendModel struct for AlipayOpenPublicMessageGroupSendModel
type AlipayOpenPublicMessageGroupSendModel struct {
	// 图文消息，当 msg_type为image-text，本参数必填。
	Articles []Article `json:"articles,omitempty"`
	// 分组ID，通过<a href=\"https://opendocs.alipay.com/apis/api_6/alipay.open.public.group.create\">alipay.open.public.group.create</a>（用户分组创建接口) 创建用户分组获取。
	GroupId *string `json:"group_id,omitempty"`
	Image   *Image  `json:"image,omitempty"`
	// 消息类型。枚举支持： * text：表示文本消息； * image-text：表示图文消息。
	MsgType *string `json:"msg_type,omitempty"`
	Text    *Text   `json:"text,omitempty"`
}

// NewAlipayOpenPublicMessageGroupSendModel instantiates a new AlipayOpenPublicMessageGroupSendModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayOpenPublicMessageGroupSendModel() *AlipayOpenPublicMessageGroupSendModel {
	this := AlipayOpenPublicMessageGroupSendModel{}
	return &this
}

// NewAlipayOpenPublicMessageGroupSendModelWithDefaults instantiates a new AlipayOpenPublicMessageGroupSendModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayOpenPublicMessageGroupSendModelWithDefaults() *AlipayOpenPublicMessageGroupSendModel {
	this := AlipayOpenPublicMessageGroupSendModel{}
	return &this
}

// GetArticles returns the Articles field value if set, zero value otherwise.
func (o *AlipayOpenPublicMessageGroupSendModel) GetArticles() []Article {
	if o == nil || IsNil(o.Articles) {
		var ret []Article
		return ret
	}
	return o.Articles
}

// GetArticlesOk returns a tuple with the Articles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) GetArticlesOk() ([]Article, bool) {
	if o == nil || IsNil(o.Articles) {
		return nil, false
	}
	return o.Articles, true
}

// HasArticles returns a boolean if a field has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) HasArticles() bool {
	if o != nil && !IsNil(o.Articles) {
		return true
	}

	return false
}

// SetArticles gets a reference to the given []Article and assigns it to the Articles field.
func (o *AlipayOpenPublicMessageGroupSendModel) SetArticles(v []Article) {
	o.Articles = v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *AlipayOpenPublicMessageGroupSendModel) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *AlipayOpenPublicMessageGroupSendModel) SetGroupId(v string) {
	o.GroupId = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *AlipayOpenPublicMessageGroupSendModel) GetImage() Image {
	if o == nil || IsNil(o.Image) {
		var ret Image
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) GetImageOk() (*Image, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given Image and assigns it to the Image field.
func (o *AlipayOpenPublicMessageGroupSendModel) SetImage(v Image) {
	o.Image = &v
}

// GetMsgType returns the MsgType field value if set, zero value otherwise.
func (o *AlipayOpenPublicMessageGroupSendModel) GetMsgType() string {
	if o == nil || IsNil(o.MsgType) {
		var ret string
		return ret
	}
	return *o.MsgType
}

// GetMsgTypeOk returns a tuple with the MsgType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) GetMsgTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MsgType) {
		return nil, false
	}
	return o.MsgType, true
}

// HasMsgType returns a boolean if a field has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) HasMsgType() bool {
	if o != nil && !IsNil(o.MsgType) {
		return true
	}

	return false
}

// SetMsgType gets a reference to the given string and assigns it to the MsgType field.
func (o *AlipayOpenPublicMessageGroupSendModel) SetMsgType(v string) {
	o.MsgType = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *AlipayOpenPublicMessageGroupSendModel) GetText() Text {
	if o == nil || IsNil(o.Text) {
		var ret Text
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) GetTextOk() (*Text, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *AlipayOpenPublicMessageGroupSendModel) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given Text and assigns it to the Text field.
func (o *AlipayOpenPublicMessageGroupSendModel) SetText(v Text) {
	o.Text = &v
}

func (o AlipayOpenPublicMessageGroupSendModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayOpenPublicMessageGroupSendModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Articles) {
		toSerialize["articles"] = o.Articles
	}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.MsgType) {
		toSerialize["msg_type"] = o.MsgType
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableAlipayOpenPublicMessageGroupSendModel struct {
	value *AlipayOpenPublicMessageGroupSendModel
	isSet bool
}

func (v NullableAlipayOpenPublicMessageGroupSendModel) Get() *AlipayOpenPublicMessageGroupSendModel {
	return v.value
}

func (v *NullableAlipayOpenPublicMessageGroupSendModel) Set(val *AlipayOpenPublicMessageGroupSendModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenPublicMessageGroupSendModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenPublicMessageGroupSendModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenPublicMessageGroupSendModel(val *AlipayOpenPublicMessageGroupSendModel) *NullableAlipayOpenPublicMessageGroupSendModel {
	return &NullableAlipayOpenPublicMessageGroupSendModel{value: val, isSet: true}
}

func (v NullableAlipayOpenPublicMessageGroupSendModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenPublicMessageGroupSendModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
