/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the VoucherUseGuideModify type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoucherUseGuideModify{}

// VoucherUseGuideModify struct for VoucherUseGuideModify
type VoucherUseGuideModify struct {
	// 券可用的小程序 appId，卡包详情页可跳转到该 appId。
	MiniAppId *string `json:"mini_app_id,omitempty"`
	// 指定跳转到 mini_app_id 时的具体页面路径。
	MiniAppPath *string `json:"mini_app_path,omitempty"`
	// 小程序服务编码，通过 alipay.open.app.appcontent.function.create(小程序服务创建)接口创建服务后获取。
	ServiceCodes []string `json:"service_codes,omitempty"`
}

// NewVoucherUseGuideModify instantiates a new VoucherUseGuideModify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoucherUseGuideModify() *VoucherUseGuideModify {
	this := VoucherUseGuideModify{}
	return &this
}

// NewVoucherUseGuideModifyWithDefaults instantiates a new VoucherUseGuideModify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoucherUseGuideModifyWithDefaults() *VoucherUseGuideModify {
	this := VoucherUseGuideModify{}
	return &this
}

// GetMiniAppId returns the MiniAppId field value if set, zero value otherwise.
func (o *VoucherUseGuideModify) GetMiniAppId() string {
	if o == nil || IsNil(o.MiniAppId) {
		var ret string
		return ret
	}
	return *o.MiniAppId
}

// GetMiniAppIdOk returns a tuple with the MiniAppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherUseGuideModify) GetMiniAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.MiniAppId) {
		return nil, false
	}
	return o.MiniAppId, true
}

// HasMiniAppId returns a boolean if a field has been set.
func (o *VoucherUseGuideModify) HasMiniAppId() bool {
	if o != nil && !IsNil(o.MiniAppId) {
		return true
	}

	return false
}

// SetMiniAppId gets a reference to the given string and assigns it to the MiniAppId field.
func (o *VoucherUseGuideModify) SetMiniAppId(v string) {
	o.MiniAppId = &v
}

// GetMiniAppPath returns the MiniAppPath field value if set, zero value otherwise.
func (o *VoucherUseGuideModify) GetMiniAppPath() string {
	if o == nil || IsNil(o.MiniAppPath) {
		var ret string
		return ret
	}
	return *o.MiniAppPath
}

// GetMiniAppPathOk returns a tuple with the MiniAppPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherUseGuideModify) GetMiniAppPathOk() (*string, bool) {
	if o == nil || IsNil(o.MiniAppPath) {
		return nil, false
	}
	return o.MiniAppPath, true
}

// HasMiniAppPath returns a boolean if a field has been set.
func (o *VoucherUseGuideModify) HasMiniAppPath() bool {
	if o != nil && !IsNil(o.MiniAppPath) {
		return true
	}

	return false
}

// SetMiniAppPath gets a reference to the given string and assigns it to the MiniAppPath field.
func (o *VoucherUseGuideModify) SetMiniAppPath(v string) {
	o.MiniAppPath = &v
}

// GetServiceCodes returns the ServiceCodes field value if set, zero value otherwise.
func (o *VoucherUseGuideModify) GetServiceCodes() []string {
	if o == nil || IsNil(o.ServiceCodes) {
		var ret []string
		return ret
	}
	return o.ServiceCodes
}

// GetServiceCodesOk returns a tuple with the ServiceCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoucherUseGuideModify) GetServiceCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.ServiceCodes) {
		return nil, false
	}
	return o.ServiceCodes, true
}

// HasServiceCodes returns a boolean if a field has been set.
func (o *VoucherUseGuideModify) HasServiceCodes() bool {
	if o != nil && !IsNil(o.ServiceCodes) {
		return true
	}

	return false
}

// SetServiceCodes gets a reference to the given []string and assigns it to the ServiceCodes field.
func (o *VoucherUseGuideModify) SetServiceCodes(v []string) {
	o.ServiceCodes = v
}

func (o VoucherUseGuideModify) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoucherUseGuideModify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MiniAppId) {
		toSerialize["mini_app_id"] = o.MiniAppId
	}
	if !IsNil(o.MiniAppPath) {
		toSerialize["mini_app_path"] = o.MiniAppPath
	}
	if !IsNil(o.ServiceCodes) {
		toSerialize["service_codes"] = o.ServiceCodes
	}
	return toSerialize, nil
}

type NullableVoucherUseGuideModify struct {
	value *VoucherUseGuideModify
	isSet bool
}

func (v NullableVoucherUseGuideModify) Get() *VoucherUseGuideModify {
	return v.value
}

func (v *NullableVoucherUseGuideModify) Set(val *VoucherUseGuideModify) {
	v.value = val
	v.isSet = true
}

func (v NullableVoucherUseGuideModify) IsSet() bool {
	return v.isSet
}

func (v *NullableVoucherUseGuideModify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoucherUseGuideModify(val *VoucherUseGuideModify) *NullableVoucherUseGuideModify {
	return &NullableVoucherUseGuideModify{value: val, isSet: true}
}

func (v NullableVoucherUseGuideModify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoucherUseGuideModify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
