/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayUserAgreementQueryDefaultResponse struct for AlipayUserAgreementQueryDefaultResponse
type AlipayUserAgreementQueryDefaultResponse struct {
	AlipayUserAgreementQueryErrorResponseModel *AlipayUserAgreementQueryErrorResponseModel
	CommonErrorType                            *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayUserAgreementQueryDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayUserAgreementQueryErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayUserAgreementQueryErrorResponseModel)
	if err == nil {
		jsonAlipayUserAgreementQueryErrorResponseModel, _ := json.Marshal(dst.AlipayUserAgreementQueryErrorResponseModel)
		if string(jsonAlipayUserAgreementQueryErrorResponseModel) == "{}" { // empty struct
			dst.AlipayUserAgreementQueryErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayUserAgreementQueryErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayUserAgreementQueryErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayUserAgreementQueryDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayUserAgreementQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayUserAgreementQueryErrorResponseModel != nil {
		return json.Marshal(&src.AlipayUserAgreementQueryErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayUserAgreementQueryDefaultResponse struct {
	value *AlipayUserAgreementQueryDefaultResponse
	isSet bool
}

func (v NullableAlipayUserAgreementQueryDefaultResponse) Get() *AlipayUserAgreementQueryDefaultResponse {
	return v.value
}

func (v *NullableAlipayUserAgreementQueryDefaultResponse) Set(val *AlipayUserAgreementQueryDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayUserAgreementQueryDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayUserAgreementQueryDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayUserAgreementQueryDefaultResponse(val *AlipayUserAgreementQueryDefaultResponse) *NullableAlipayUserAgreementQueryDefaultResponse {
	return &NullableAlipayUserAgreementQueryDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayUserAgreementQueryDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayUserAgreementQueryDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
