/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayOpenPublicLifeLabelModifyDefaultResponse struct for AlipayOpenPublicLifeLabelModifyDefaultResponse
type AlipayOpenPublicLifeLabelModifyDefaultResponse struct {
	AlipayOpenPublicLifeLabelModifyErrorResponseModel *AlipayOpenPublicLifeLabelModifyErrorResponseModel
	CommonErrorType                                   *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayOpenPublicLifeLabelModifyDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayOpenPublicLifeLabelModifyErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayOpenPublicLifeLabelModifyErrorResponseModel)
	if err == nil {
		jsonAlipayOpenPublicLifeLabelModifyErrorResponseModel, _ := json.Marshal(dst.AlipayOpenPublicLifeLabelModifyErrorResponseModel)
		if string(jsonAlipayOpenPublicLifeLabelModifyErrorResponseModel) == "{}" { // empty struct
			dst.AlipayOpenPublicLifeLabelModifyErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayOpenPublicLifeLabelModifyErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayOpenPublicLifeLabelModifyErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayOpenPublicLifeLabelModifyDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayOpenPublicLifeLabelModifyDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayOpenPublicLifeLabelModifyErrorResponseModel != nil {
		return json.Marshal(&src.AlipayOpenPublicLifeLabelModifyErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayOpenPublicLifeLabelModifyDefaultResponse struct {
	value *AlipayOpenPublicLifeLabelModifyDefaultResponse
	isSet bool
}

func (v NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) Get() *AlipayOpenPublicLifeLabelModifyDefaultResponse {
	return v.value
}

func (v *NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) Set(val *AlipayOpenPublicLifeLabelModifyDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenPublicLifeLabelModifyDefaultResponse(val *AlipayOpenPublicLifeLabelModifyDefaultResponse) *NullableAlipayOpenPublicLifeLabelModifyDefaultResponse {
	return &NullableAlipayOpenPublicLifeLabelModifyDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenPublicLifeLabelModifyDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
