/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AlipayOpenSearchBoxactivityOfflineModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayOpenSearchBoxactivityOfflineModel{}

// AlipayOpenSearchBoxactivityOfflineModel struct for AlipayOpenSearchBoxactivityOfflineModel
type AlipayOpenSearchBoxactivityOfflineModel struct {
	// 搜索直达活动id
	BoxActivityId *string `json:"box_activity_id,omitempty"`
	// 商户id，代运营模式下传入。代运营模式，需要服务商已获得商家\"运营支付宝小程序\"授权。
	MerchantId *string `json:"merchant_id,omitempty"`
}

// NewAlipayOpenSearchBoxactivityOfflineModel instantiates a new AlipayOpenSearchBoxactivityOfflineModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayOpenSearchBoxactivityOfflineModel() *AlipayOpenSearchBoxactivityOfflineModel {
	this := AlipayOpenSearchBoxactivityOfflineModel{}
	return &this
}

// NewAlipayOpenSearchBoxactivityOfflineModelWithDefaults instantiates a new AlipayOpenSearchBoxactivityOfflineModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayOpenSearchBoxactivityOfflineModelWithDefaults() *AlipayOpenSearchBoxactivityOfflineModel {
	this := AlipayOpenSearchBoxactivityOfflineModel{}
	return &this
}

// GetBoxActivityId returns the BoxActivityId field value if set, zero value otherwise.
func (o *AlipayOpenSearchBoxactivityOfflineModel) GetBoxActivityId() string {
	if o == nil || IsNil(o.BoxActivityId) {
		var ret string
		return ret
	}
	return *o.BoxActivityId
}

// GetBoxActivityIdOk returns a tuple with the BoxActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenSearchBoxactivityOfflineModel) GetBoxActivityIdOk() (*string, bool) {
	if o == nil || IsNil(o.BoxActivityId) {
		return nil, false
	}
	return o.BoxActivityId, true
}

// HasBoxActivityId returns a boolean if a field has been set.
func (o *AlipayOpenSearchBoxactivityOfflineModel) HasBoxActivityId() bool {
	if o != nil && !IsNil(o.BoxActivityId) {
		return true
	}

	return false
}

// SetBoxActivityId gets a reference to the given string and assigns it to the BoxActivityId field.
func (o *AlipayOpenSearchBoxactivityOfflineModel) SetBoxActivityId(v string) {
	o.BoxActivityId = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *AlipayOpenSearchBoxactivityOfflineModel) GetMerchantId() string {
	if o == nil || IsNil(o.MerchantId) {
		var ret string
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenSearchBoxactivityOfflineModel) GetMerchantIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantId) {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *AlipayOpenSearchBoxactivityOfflineModel) HasMerchantId() bool {
	if o != nil && !IsNil(o.MerchantId) {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given string and assigns it to the MerchantId field.
func (o *AlipayOpenSearchBoxactivityOfflineModel) SetMerchantId(v string) {
	o.MerchantId = &v
}

func (o AlipayOpenSearchBoxactivityOfflineModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayOpenSearchBoxactivityOfflineModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BoxActivityId) {
		toSerialize["box_activity_id"] = o.BoxActivityId
	}
	if !IsNil(o.MerchantId) {
		toSerialize["merchant_id"] = o.MerchantId
	}
	return toSerialize, nil
}

type NullableAlipayOpenSearchBoxactivityOfflineModel struct {
	value *AlipayOpenSearchBoxactivityOfflineModel
	isSet bool
}

func (v NullableAlipayOpenSearchBoxactivityOfflineModel) Get() *AlipayOpenSearchBoxactivityOfflineModel {
	return v.value
}

func (v *NullableAlipayOpenSearchBoxactivityOfflineModel) Set(val *AlipayOpenSearchBoxactivityOfflineModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenSearchBoxactivityOfflineModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenSearchBoxactivityOfflineModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenSearchBoxactivityOfflineModel(val *AlipayOpenSearchBoxactivityOfflineModel) *NullableAlipayOpenSearchBoxactivityOfflineModel {
	return &NullableAlipayOpenSearchBoxactivityOfflineModel{value: val, isSet: true}
}

func (v NullableAlipayOpenSearchBoxactivityOfflineModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenSearchBoxactivityOfflineModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


