/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ZhimaMerchantSubsidiariesCloseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZhimaMerchantSubsidiariesCloseModel{}

// ZhimaMerchantSubsidiariesCloseModel struct for ZhimaMerchantSubsidiariesCloseModel
type ZhimaMerchantSubsidiariesCloseModel struct {
	// 工单标识
	OrderNo *string `json:"order_no,omitempty"`
}

// NewZhimaMerchantSubsidiariesCloseModel instantiates a new ZhimaMerchantSubsidiariesCloseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZhimaMerchantSubsidiariesCloseModel() *ZhimaMerchantSubsidiariesCloseModel {
	this := ZhimaMerchantSubsidiariesCloseModel{}
	return &this
}

// NewZhimaMerchantSubsidiariesCloseModelWithDefaults instantiates a new ZhimaMerchantSubsidiariesCloseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZhimaMerchantSubsidiariesCloseModelWithDefaults() *ZhimaMerchantSubsidiariesCloseModel {
	this := ZhimaMerchantSubsidiariesCloseModel{}
	return &this
}

// GetOrderNo returns the OrderNo field value if set, zero value otherwise.
func (o *ZhimaMerchantSubsidiariesCloseModel) GetOrderNo() string {
	if o == nil || IsNil(o.OrderNo) {
		var ret string
		return ret
	}
	return *o.OrderNo
}

// GetOrderNoOk returns a tuple with the OrderNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZhimaMerchantSubsidiariesCloseModel) GetOrderNoOk() (*string, bool) {
	if o == nil || IsNil(o.OrderNo) {
		return nil, false
	}
	return o.OrderNo, true
}

// HasOrderNo returns a boolean if a field has been set.
func (o *ZhimaMerchantSubsidiariesCloseModel) HasOrderNo() bool {
	if o != nil && !IsNil(o.OrderNo) {
		return true
	}

	return false
}

// SetOrderNo gets a reference to the given string and assigns it to the OrderNo field.
func (o *ZhimaMerchantSubsidiariesCloseModel) SetOrderNo(v string) {
	o.OrderNo = &v
}

func (o ZhimaMerchantSubsidiariesCloseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZhimaMerchantSubsidiariesCloseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderNo) {
		toSerialize["order_no"] = o.OrderNo
	}
	return toSerialize, nil
}

type NullableZhimaMerchantSubsidiariesCloseModel struct {
	value *ZhimaMerchantSubsidiariesCloseModel
	isSet bool
}

func (v NullableZhimaMerchantSubsidiariesCloseModel) Get() *ZhimaMerchantSubsidiariesCloseModel {
	return v.value
}

func (v *NullableZhimaMerchantSubsidiariesCloseModel) Set(val *ZhimaMerchantSubsidiariesCloseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableZhimaMerchantSubsidiariesCloseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableZhimaMerchantSubsidiariesCloseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZhimaMerchantSubsidiariesCloseModel(val *ZhimaMerchantSubsidiariesCloseModel) *NullableZhimaMerchantSubsidiariesCloseModel {
	return &NullableZhimaMerchantSubsidiariesCloseModel{value: val, isSet: true}
}

func (v NullableZhimaMerchantSubsidiariesCloseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZhimaMerchantSubsidiariesCloseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


