/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
	"fmt"
)

// AlipayEbppInvoiceExpenseProgressSyncDefaultResponse struct for AlipayEbppInvoiceExpenseProgressSyncDefaultResponse
type AlipayEbppInvoiceExpenseProgressSyncDefaultResponse struct {
	AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel *AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel
	CommonErrorType                                        *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel)
	if err == nil {
		jsonAlipayEbppInvoiceExpenseProgressSyncErrorResponseModel, _ := json.Marshal(dst.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel)
		if string(jsonAlipayEbppInvoiceExpenseProgressSyncErrorResponseModel) == "{}" { // empty struct
			dst.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType)
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayEbppInvoiceExpenseProgressSyncDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel != nil {
		return json.Marshal(&src.AlipayEbppInvoiceExpenseProgressSyncErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse struct {
	value *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse
	isSet bool
}

func (v NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) Get() *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse {
	return v.value
}

func (v *NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) Set(val *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse(val *AlipayEbppInvoiceExpenseProgressSyncDefaultResponse) *NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse {
	return &NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayEbppInvoiceExpenseProgressSyncDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
