/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)


// AlipayIserviceCcmServiceInitializeDefaultResponse struct for AlipayIserviceCcmServiceInitializeDefaultResponse
type AlipayIserviceCcmServiceInitializeDefaultResponse struct {
	AlipayIserviceCcmServiceInitializeErrorResponseModel *AlipayIserviceCcmServiceInitializeErrorResponseModel
	CommonErrorType *CommonErrorType
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AlipayIserviceCcmServiceInitializeDefaultResponse) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into AlipayIserviceCcmServiceInitializeErrorResponseModel
	err = json.Unmarshal(data, &dst.AlipayIserviceCcmServiceInitializeErrorResponseModel);
	if err == nil {
		jsonAlipayIserviceCcmServiceInitializeErrorResponseModel, _ := json.Marshal(dst.AlipayIserviceCcmServiceInitializeErrorResponseModel)
		if string(jsonAlipayIserviceCcmServiceInitializeErrorResponseModel) == "{}" { // empty struct
			dst.AlipayIserviceCcmServiceInitializeErrorResponseModel = nil
		} else {
			return nil // data stored in dst.AlipayIserviceCcmServiceInitializeErrorResponseModel, return on the first match
		}
	} else {
		dst.AlipayIserviceCcmServiceInitializeErrorResponseModel = nil
	}

	// try to unmarshal JSON data into CommonErrorType
	err = json.Unmarshal(data, &dst.CommonErrorType);
	if err == nil {
		jsonCommonErrorType, _ := json.Marshal(dst.CommonErrorType)
		if string(jsonCommonErrorType) == "{}" { // empty struct
			dst.CommonErrorType = nil
		} else {
			return nil // data stored in dst.CommonErrorType, return on the first match
		}
	} else {
		dst.CommonErrorType = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AlipayIserviceCcmServiceInitializeDefaultResponse)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AlipayIserviceCcmServiceInitializeDefaultResponse) MarshalJSON() ([]byte, error) {
	if src.AlipayIserviceCcmServiceInitializeErrorResponseModel != nil {
		return json.Marshal(&src.AlipayIserviceCcmServiceInitializeErrorResponseModel)
	}

	if src.CommonErrorType != nil {
		return json.Marshal(&src.CommonErrorType)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableAlipayIserviceCcmServiceInitializeDefaultResponse struct {
	value *AlipayIserviceCcmServiceInitializeDefaultResponse
	isSet bool
}

func (v NullableAlipayIserviceCcmServiceInitializeDefaultResponse) Get() *AlipayIserviceCcmServiceInitializeDefaultResponse {
	return v.value
}

func (v *NullableAlipayIserviceCcmServiceInitializeDefaultResponse) Set(val *AlipayIserviceCcmServiceInitializeDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayIserviceCcmServiceInitializeDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayIserviceCcmServiceInitializeDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayIserviceCcmServiceInitializeDefaultResponse(val *AlipayIserviceCcmServiceInitializeDefaultResponse) *NullableAlipayIserviceCcmServiceInitializeDefaultResponse {
	return &NullableAlipayIserviceCcmServiceInitializeDefaultResponse{value: val, isSet: true}
}

func (v NullableAlipayIserviceCcmServiceInitializeDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayIserviceCcmServiceInitializeDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


