/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AlipayOpenMiniBaseinfoModifyModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayOpenMiniBaseinfoModifyModel{}

// AlipayOpenMiniBaseinfoModifyModel struct for AlipayOpenMiniBaseinfoModifyModel
type AlipayOpenMiniBaseinfoModifyModel struct {
	// 11_12;12_13。小程序类目，格式为 第一个一级类目_第一个二级类目;第二个一级类目_第二个二级类目，详细类目可以参考<a href=\"https://docs.open.alipay.com/api_49/alipay.open.mini.category.query\">https://docs.open.alipay.com/api_49/alipay.open.mini.category.query</a>接口查询mini_category_list 。
	AppCategoryIds *string `json:"app_category_ids,omitempty"`
	// 小程序描述，长度限制 20~400 个字符。 如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。如果前期没有设置过该信息，则本次为必填。可通过<a href=\"https://opendocs.alipay.com/mini/03l21r\">https://opendocs.alipay.com/mini/03l21r</a>查询当前小程序信息
	AppDesc *string `json:"app_desc,omitempty"`
	// 小程序应用英文名称。长度限制 3~30 个字符，仅支持包含中文、数字、英文、下划线、+、-。 如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。如果前期没有设置过该信息，则本次为必填。可通过<a href=\"https://opendocs.alipay.com/mini/03l21r?pathHash=36d314be&scene=common\">alipay.open.mini.baseinfo.query</a>查询当前小程序信息
	AppEnglishName *string `json:"app_english_name,omitempty"`
	// 小程序名称。长度限制 3~30 个字符，仅支持包含中文、数字、英文、下划线、+、-。 如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。如果前期没有设置过该信息，则本次为必填。可通过<a href=\"https://opendocs.alipay.com/mini/03l21r?pathHash=36d314be&scene=common \">alipay.open.mini.baseinfo.query</a>查询当前小程序信息
	AppName *string `json:"app_name,omitempty"`
	// 小程序简介，一句话描述小程序功能，长度限制 10~32个字符。 如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。如果前期没有设置过该信息，则本次为必填。可通过<a href=\"https://opendocs.alipay.com/mini/03l21r?pathHash=36d314be&scene=common\">alipay.open.mini.baseinfo.query</a>查询当前小程序信息
	AppSlogan *string `json:"app_slogan,omitempty"`
	// 新小程序前台类目，格式为 第一个一级类目_第一个二级类目;第二个一级类目_第二个二级类目_第二个三级类目，详细类目可以通过 <a href=\"https://docs.open.alipay.com/api_49/alipay.open.mini.category.query\">https://docs.open.alipay.com/api_49/alipay.open.mini.category.query</a> 接口查询mini_category_list。 如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。如果前期没有设置过该信息，则本次为必填。可通过<a href=\"https://opendocs.alipay.com/mini/03l21r\">https://opendocs.alipay.com/mini/03l21r</a>查询当前小程序信息 注意：个人开发者不得使用企业类目。
	MiniCategoryIds *string `json:"mini_category_ids,omitempty"`
	// 小程序客服邮箱，如果不填默认采用当前小程序的应用客服邮箱，小程序客服电话和邮箱至少输入一个。如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。 注意：2021年7月1日后，该字段将逐步灰度为可选字段，请按可选开发。
	ServiceEmail *string `json:"service_email,omitempty"`
	// 小程序客服电话，长度限制5~30个字符，仅支持包含数字和-。如果不填默认采用当前小程序的应用客服电话，小程序客服电话和邮箱至少输入一个。如果前期已经设置过该信息，本次可不填，平台将会为你默认上传该信息。 注意：2021年7月1日后，该字段将逐步灰度为必填字段，请按必填开发。
	ServicePhone *string `json:"service_phone,omitempty"`
}

// NewAlipayOpenMiniBaseinfoModifyModel instantiates a new AlipayOpenMiniBaseinfoModifyModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayOpenMiniBaseinfoModifyModel() *AlipayOpenMiniBaseinfoModifyModel {
	this := AlipayOpenMiniBaseinfoModifyModel{}
	return &this
}

// NewAlipayOpenMiniBaseinfoModifyModelWithDefaults instantiates a new AlipayOpenMiniBaseinfoModifyModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayOpenMiniBaseinfoModifyModelWithDefaults() *AlipayOpenMiniBaseinfoModifyModel {
	this := AlipayOpenMiniBaseinfoModifyModel{}
	return &this
}

// GetAppCategoryIds returns the AppCategoryIds field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppCategoryIds() string {
	if o == nil || IsNil(o.AppCategoryIds) {
		var ret string
		return ret
	}
	return *o.AppCategoryIds
}

// GetAppCategoryIdsOk returns a tuple with the AppCategoryIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppCategoryIdsOk() (*string, bool) {
	if o == nil || IsNil(o.AppCategoryIds) {
		return nil, false
	}
	return o.AppCategoryIds, true
}

// HasAppCategoryIds returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasAppCategoryIds() bool {
	if o != nil && !IsNil(o.AppCategoryIds) {
		return true
	}

	return false
}

// SetAppCategoryIds gets a reference to the given string and assigns it to the AppCategoryIds field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetAppCategoryIds(v string) {
	o.AppCategoryIds = &v
}

// GetAppDesc returns the AppDesc field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppDesc() string {
	if o == nil || IsNil(o.AppDesc) {
		var ret string
		return ret
	}
	return *o.AppDesc
}

// GetAppDescOk returns a tuple with the AppDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppDescOk() (*string, bool) {
	if o == nil || IsNil(o.AppDesc) {
		return nil, false
	}
	return o.AppDesc, true
}

// HasAppDesc returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasAppDesc() bool {
	if o != nil && !IsNil(o.AppDesc) {
		return true
	}

	return false
}

// SetAppDesc gets a reference to the given string and assigns it to the AppDesc field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetAppDesc(v string) {
	o.AppDesc = &v
}

// GetAppEnglishName returns the AppEnglishName field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppEnglishName() string {
	if o == nil || IsNil(o.AppEnglishName) {
		var ret string
		return ret
	}
	return *o.AppEnglishName
}

// GetAppEnglishNameOk returns a tuple with the AppEnglishName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppEnglishNameOk() (*string, bool) {
	if o == nil || IsNil(o.AppEnglishName) {
		return nil, false
	}
	return o.AppEnglishName, true
}

// HasAppEnglishName returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasAppEnglishName() bool {
	if o != nil && !IsNil(o.AppEnglishName) {
		return true
	}

	return false
}

// SetAppEnglishName gets a reference to the given string and assigns it to the AppEnglishName field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetAppEnglishName(v string) {
	o.AppEnglishName = &v
}

// GetAppName returns the AppName field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppName() string {
	if o == nil || IsNil(o.AppName) {
		var ret string
		return ret
	}
	return *o.AppName
}

// GetAppNameOk returns a tuple with the AppName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppNameOk() (*string, bool) {
	if o == nil || IsNil(o.AppName) {
		return nil, false
	}
	return o.AppName, true
}

// HasAppName returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasAppName() bool {
	if o != nil && !IsNil(o.AppName) {
		return true
	}

	return false
}

// SetAppName gets a reference to the given string and assigns it to the AppName field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetAppName(v string) {
	o.AppName = &v
}

// GetAppSlogan returns the AppSlogan field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppSlogan() string {
	if o == nil || IsNil(o.AppSlogan) {
		var ret string
		return ret
	}
	return *o.AppSlogan
}

// GetAppSloganOk returns a tuple with the AppSlogan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetAppSloganOk() (*string, bool) {
	if o == nil || IsNil(o.AppSlogan) {
		return nil, false
	}
	return o.AppSlogan, true
}

// HasAppSlogan returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasAppSlogan() bool {
	if o != nil && !IsNil(o.AppSlogan) {
		return true
	}

	return false
}

// SetAppSlogan gets a reference to the given string and assigns it to the AppSlogan field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetAppSlogan(v string) {
	o.AppSlogan = &v
}

// GetMiniCategoryIds returns the MiniCategoryIds field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetMiniCategoryIds() string {
	if o == nil || IsNil(o.MiniCategoryIds) {
		var ret string
		return ret
	}
	return *o.MiniCategoryIds
}

// GetMiniCategoryIdsOk returns a tuple with the MiniCategoryIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetMiniCategoryIdsOk() (*string, bool) {
	if o == nil || IsNil(o.MiniCategoryIds) {
		return nil, false
	}
	return o.MiniCategoryIds, true
}

// HasMiniCategoryIds returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasMiniCategoryIds() bool {
	if o != nil && !IsNil(o.MiniCategoryIds) {
		return true
	}

	return false
}

// SetMiniCategoryIds gets a reference to the given string and assigns it to the MiniCategoryIds field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetMiniCategoryIds(v string) {
	o.MiniCategoryIds = &v
}

// GetServiceEmail returns the ServiceEmail field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetServiceEmail() string {
	if o == nil || IsNil(o.ServiceEmail) {
		var ret string
		return ret
	}
	return *o.ServiceEmail
}

// GetServiceEmailOk returns a tuple with the ServiceEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetServiceEmailOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceEmail) {
		return nil, false
	}
	return o.ServiceEmail, true
}

// HasServiceEmail returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasServiceEmail() bool {
	if o != nil && !IsNil(o.ServiceEmail) {
		return true
	}

	return false
}

// SetServiceEmail gets a reference to the given string and assigns it to the ServiceEmail field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetServiceEmail(v string) {
	o.ServiceEmail = &v
}

// GetServicePhone returns the ServicePhone field value if set, zero value otherwise.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetServicePhone() string {
	if o == nil || IsNil(o.ServicePhone) {
		var ret string
		return ret
	}
	return *o.ServicePhone
}

// GetServicePhoneOk returns a tuple with the ServicePhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) GetServicePhoneOk() (*string, bool) {
	if o == nil || IsNil(o.ServicePhone) {
		return nil, false
	}
	return o.ServicePhone, true
}

// HasServicePhone returns a boolean if a field has been set.
func (o *AlipayOpenMiniBaseinfoModifyModel) HasServicePhone() bool {
	if o != nil && !IsNil(o.ServicePhone) {
		return true
	}

	return false
}

// SetServicePhone gets a reference to the given string and assigns it to the ServicePhone field.
func (o *AlipayOpenMiniBaseinfoModifyModel) SetServicePhone(v string) {
	o.ServicePhone = &v
}

func (o AlipayOpenMiniBaseinfoModifyModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayOpenMiniBaseinfoModifyModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppCategoryIds) {
		toSerialize["app_category_ids"] = o.AppCategoryIds
	}
	if !IsNil(o.AppDesc) {
		toSerialize["app_desc"] = o.AppDesc
	}
	if !IsNil(o.AppEnglishName) {
		toSerialize["app_english_name"] = o.AppEnglishName
	}
	if !IsNil(o.AppName) {
		toSerialize["app_name"] = o.AppName
	}
	if !IsNil(o.AppSlogan) {
		toSerialize["app_slogan"] = o.AppSlogan
	}
	if !IsNil(o.MiniCategoryIds) {
		toSerialize["mini_category_ids"] = o.MiniCategoryIds
	}
	if !IsNil(o.ServiceEmail) {
		toSerialize["service_email"] = o.ServiceEmail
	}
	if !IsNil(o.ServicePhone) {
		toSerialize["service_phone"] = o.ServicePhone
	}
	return toSerialize, nil
}

type NullableAlipayOpenMiniBaseinfoModifyModel struct {
	value *AlipayOpenMiniBaseinfoModifyModel
	isSet bool
}

func (v NullableAlipayOpenMiniBaseinfoModifyModel) Get() *AlipayOpenMiniBaseinfoModifyModel {
	return v.value
}

func (v *NullableAlipayOpenMiniBaseinfoModifyModel) Set(val *AlipayOpenMiniBaseinfoModifyModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayOpenMiniBaseinfoModifyModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayOpenMiniBaseinfoModifyModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayOpenMiniBaseinfoModifyModel(val *AlipayOpenMiniBaseinfoModifyModel) *NullableAlipayOpenMiniBaseinfoModifyModel {
	return &NullableAlipayOpenMiniBaseinfoModifyModel{value: val, isSet: true}
}

func (v NullableAlipayOpenMiniBaseinfoModifyModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayOpenMiniBaseinfoModifyModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


