/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the AlipayPcreditHuabeiAuthRefundApplyResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayPcreditHuabeiAuthRefundApplyResponseModel{}

// AlipayPcreditHuabeiAuthRefundApplyResponseModel struct for AlipayPcreditHuabeiAuthRefundApplyResponseModel
type AlipayPcreditHuabeiAuthRefundApplyResponseModel struct {
	// 授权支付单ID
	AuthOptId *string `json:"auth_opt_id,omitempty"`
	// 退款操作错误原因描述
	FailReason *string `json:"fail_reason,omitempty"`
	// 外部请求号
	OutRequestNo *string `json:"out_request_no,omitempty"`
	// 是否可重试
	Retry *bool `json:"retry,omitempty"`
}

// NewAlipayPcreditHuabeiAuthRefundApplyResponseModel instantiates a new AlipayPcreditHuabeiAuthRefundApplyResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayPcreditHuabeiAuthRefundApplyResponseModel() *AlipayPcreditHuabeiAuthRefundApplyResponseModel {
	this := AlipayPcreditHuabeiAuthRefundApplyResponseModel{}
	return &this
}

// NewAlipayPcreditHuabeiAuthRefundApplyResponseModelWithDefaults instantiates a new AlipayPcreditHuabeiAuthRefundApplyResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayPcreditHuabeiAuthRefundApplyResponseModelWithDefaults() *AlipayPcreditHuabeiAuthRefundApplyResponseModel {
	this := AlipayPcreditHuabeiAuthRefundApplyResponseModel{}
	return &this
}

// GetAuthOptId returns the AuthOptId field value if set, zero value otherwise.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetAuthOptId() string {
	if o == nil || IsNil(o.AuthOptId) {
		var ret string
		return ret
	}
	return *o.AuthOptId
}

// GetAuthOptIdOk returns a tuple with the AuthOptId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetAuthOptIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthOptId) {
		return nil, false
	}
	return o.AuthOptId, true
}

// HasAuthOptId returns a boolean if a field has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) HasAuthOptId() bool {
	if o != nil && !IsNil(o.AuthOptId) {
		return true
	}

	return false
}

// SetAuthOptId gets a reference to the given string and assigns it to the AuthOptId field.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) SetAuthOptId(v string) {
	o.AuthOptId = &v
}

// GetFailReason returns the FailReason field value if set, zero value otherwise.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetFailReason() string {
	if o == nil || IsNil(o.FailReason) {
		var ret string
		return ret
	}
	return *o.FailReason
}

// GetFailReasonOk returns a tuple with the FailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetFailReasonOk() (*string, bool) {
	if o == nil || IsNil(o.FailReason) {
		return nil, false
	}
	return o.FailReason, true
}

// HasFailReason returns a boolean if a field has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) HasFailReason() bool {
	if o != nil && !IsNil(o.FailReason) {
		return true
	}

	return false
}

// SetFailReason gets a reference to the given string and assigns it to the FailReason field.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) SetFailReason(v string) {
	o.FailReason = &v
}

// GetOutRequestNo returns the OutRequestNo field value if set, zero value otherwise.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetOutRequestNo() string {
	if o == nil || IsNil(o.OutRequestNo) {
		var ret string
		return ret
	}
	return *o.OutRequestNo
}

// GetOutRequestNoOk returns a tuple with the OutRequestNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetOutRequestNoOk() (*string, bool) {
	if o == nil || IsNil(o.OutRequestNo) {
		return nil, false
	}
	return o.OutRequestNo, true
}

// HasOutRequestNo returns a boolean if a field has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) HasOutRequestNo() bool {
	if o != nil && !IsNil(o.OutRequestNo) {
		return true
	}

	return false
}

// SetOutRequestNo gets a reference to the given string and assigns it to the OutRequestNo field.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) SetOutRequestNo(v string) {
	o.OutRequestNo = &v
}

// GetRetry returns the Retry field value if set, zero value otherwise.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetRetry() bool {
	if o == nil || IsNil(o.Retry) {
		var ret bool
		return ret
	}
	return *o.Retry
}

// GetRetryOk returns a tuple with the Retry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) GetRetryOk() (*bool, bool) {
	if o == nil || IsNil(o.Retry) {
		return nil, false
	}
	return o.Retry, true
}

// HasRetry returns a boolean if a field has been set.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) HasRetry() bool {
	if o != nil && !IsNil(o.Retry) {
		return true
	}

	return false
}

// SetRetry gets a reference to the given bool and assigns it to the Retry field.
func (o *AlipayPcreditHuabeiAuthRefundApplyResponseModel) SetRetry(v bool) {
	o.Retry = &v
}

func (o AlipayPcreditHuabeiAuthRefundApplyResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayPcreditHuabeiAuthRefundApplyResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthOptId) {
		toSerialize["auth_opt_id"] = o.AuthOptId
	}
	if !IsNil(o.FailReason) {
		toSerialize["fail_reason"] = o.FailReason
	}
	if !IsNil(o.OutRequestNo) {
		toSerialize["out_request_no"] = o.OutRequestNo
	}
	if !IsNil(o.Retry) {
		toSerialize["retry"] = o.Retry
	}
	return toSerialize, nil
}

type NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel struct {
	value *AlipayPcreditHuabeiAuthRefundApplyResponseModel
	isSet bool
}

func (v NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) Get() *AlipayPcreditHuabeiAuthRefundApplyResponseModel {
	return v.value
}

func (v *NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) Set(val *AlipayPcreditHuabeiAuthRefundApplyResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayPcreditHuabeiAuthRefundApplyResponseModel(val *AlipayPcreditHuabeiAuthRefundApplyResponseModel) *NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel {
	return &NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel{value: val, isSet: true}
}

func (v NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayPcreditHuabeiAuthRefundApplyResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
