/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AlipayMobilePublicMenuGetResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayMobilePublicMenuGetResponseModel{}

// AlipayMobilePublicMenuGetResponseModel struct for AlipayMobilePublicMenuGetResponseModel
type AlipayMobilePublicMenuGetResponseModel struct {
	// success
	Code *string `json:"code,omitempty"`
	// 菜单内容
	MenuContent *string `json:"menu_content,omitempty"`
	// 成功
	Msg *string `json:"msg,omitempty"`
}

// NewAlipayMobilePublicMenuGetResponseModel instantiates a new AlipayMobilePublicMenuGetResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayMobilePublicMenuGetResponseModel() *AlipayMobilePublicMenuGetResponseModel {
	this := AlipayMobilePublicMenuGetResponseModel{}
	return &this
}

// NewAlipayMobilePublicMenuGetResponseModelWithDefaults instantiates a new AlipayMobilePublicMenuGetResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayMobilePublicMenuGetResponseModelWithDefaults() *AlipayMobilePublicMenuGetResponseModel {
	this := AlipayMobilePublicMenuGetResponseModel{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AlipayMobilePublicMenuGetResponseModel) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *AlipayMobilePublicMenuGetResponseModel) SetCode(v string) {
	o.Code = &v
}

// GetMenuContent returns the MenuContent field value if set, zero value otherwise.
func (o *AlipayMobilePublicMenuGetResponseModel) GetMenuContent() string {
	if o == nil || IsNil(o.MenuContent) {
		var ret string
		return ret
	}
	return *o.MenuContent
}

// GetMenuContentOk returns a tuple with the MenuContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) GetMenuContentOk() (*string, bool) {
	if o == nil || IsNil(o.MenuContent) {
		return nil, false
	}
	return o.MenuContent, true
}

// HasMenuContent returns a boolean if a field has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) HasMenuContent() bool {
	if o != nil && !IsNil(o.MenuContent) {
		return true
	}

	return false
}

// SetMenuContent gets a reference to the given string and assigns it to the MenuContent field.
func (o *AlipayMobilePublicMenuGetResponseModel) SetMenuContent(v string) {
	o.MenuContent = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *AlipayMobilePublicMenuGetResponseModel) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *AlipayMobilePublicMenuGetResponseModel) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *AlipayMobilePublicMenuGetResponseModel) SetMsg(v string) {
	o.Msg = &v
}

func (o AlipayMobilePublicMenuGetResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayMobilePublicMenuGetResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.MenuContent) {
		toSerialize["menu_content"] = o.MenuContent
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	return toSerialize, nil
}

type NullableAlipayMobilePublicMenuGetResponseModel struct {
	value *AlipayMobilePublicMenuGetResponseModel
	isSet bool
}

func (v NullableAlipayMobilePublicMenuGetResponseModel) Get() *AlipayMobilePublicMenuGetResponseModel {
	return v.value
}

func (v *NullableAlipayMobilePublicMenuGetResponseModel) Set(val *AlipayMobilePublicMenuGetResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayMobilePublicMenuGetResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayMobilePublicMenuGetResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayMobilePublicMenuGetResponseModel(val *AlipayMobilePublicMenuGetResponseModel) *NullableAlipayMobilePublicMenuGetResponseModel {
	return &NullableAlipayMobilePublicMenuGetResponseModel{value: val, isSet: true}
}

func (v NullableAlipayMobilePublicMenuGetResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayMobilePublicMenuGetResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


