/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the EnterpriseOpenRuleInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnterpriseOpenRuleInfo{}

// EnterpriseOpenRuleInfo struct for EnterpriseOpenRuleInfo
type EnterpriseOpenRuleInfo struct {
	// 企业ID
	EnterpriseId *string `json:"enterprise_id,omitempty"`
	// 当前生效和下次生效的开票规则记录
	EnterpriseOpenRuleRecordInfoList []EnterpriseOpenRuleRecordInfo `json:"enterprise_open_rule_record_info_list,omitempty"`
	// 开票规则绑定关系
	EnterpriseOpenRuleRelationInfoList []EnterpriseOpenRuleRelationInfo `json:"enterprise_open_rule_relation_info_list,omitempty"`
	// 创建时间
	GmtCreate *string `json:"gmt_create,omitempty"`
	// 修改时间
	GmtModified *string `json:"gmt_modified,omitempty"`
	// 开票规则ID
	InvoiceRuleId *string `json:"invoice_rule_id,omitempty"`
	// 开票规则名称
	InvoiceRuleName *string `json:"invoice_rule_name,omitempty"`
	// 所有者ID（企业情况下即为企业ID）。
	OwnerId *string `json:"owner_id,omitempty"`
	// \"销方类型：TP开票、商户开票、商户优先枚举定义：MERCHANT（商户）、TP（TP）\"
	SellerType *string `json:"seller_type,omitempty"`
}

// NewEnterpriseOpenRuleInfo instantiates a new EnterpriseOpenRuleInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnterpriseOpenRuleInfo() *EnterpriseOpenRuleInfo {
	this := EnterpriseOpenRuleInfo{}
	return &this
}

// NewEnterpriseOpenRuleInfoWithDefaults instantiates a new EnterpriseOpenRuleInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnterpriseOpenRuleInfoWithDefaults() *EnterpriseOpenRuleInfo {
	this := EnterpriseOpenRuleInfo{}
	return &this
}

// GetEnterpriseId returns the EnterpriseId field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseId() string {
	if o == nil || IsNil(o.EnterpriseId) {
		var ret string
		return ret
	}
	return *o.EnterpriseId
}

// GetEnterpriseIdOk returns a tuple with the EnterpriseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnterpriseId) {
		return nil, false
	}
	return o.EnterpriseId, true
}

// HasEnterpriseId returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasEnterpriseId() bool {
	if o != nil && !IsNil(o.EnterpriseId) {
		return true
	}

	return false
}

// SetEnterpriseId gets a reference to the given string and assigns it to the EnterpriseId field.
func (o *EnterpriseOpenRuleInfo) SetEnterpriseId(v string) {
	o.EnterpriseId = &v
}

// GetEnterpriseOpenRuleRecordInfoList returns the EnterpriseOpenRuleRecordInfoList field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseOpenRuleRecordInfoList() []EnterpriseOpenRuleRecordInfo {
	if o == nil || IsNil(o.EnterpriseOpenRuleRecordInfoList) {
		var ret []EnterpriseOpenRuleRecordInfo
		return ret
	}
	return o.EnterpriseOpenRuleRecordInfoList
}

// GetEnterpriseOpenRuleRecordInfoListOk returns a tuple with the EnterpriseOpenRuleRecordInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseOpenRuleRecordInfoListOk() ([]EnterpriseOpenRuleRecordInfo, bool) {
	if o == nil || IsNil(o.EnterpriseOpenRuleRecordInfoList) {
		return nil, false
	}
	return o.EnterpriseOpenRuleRecordInfoList, true
}

// HasEnterpriseOpenRuleRecordInfoList returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasEnterpriseOpenRuleRecordInfoList() bool {
	if o != nil && !IsNil(o.EnterpriseOpenRuleRecordInfoList) {
		return true
	}

	return false
}

// SetEnterpriseOpenRuleRecordInfoList gets a reference to the given []EnterpriseOpenRuleRecordInfo and assigns it to the EnterpriseOpenRuleRecordInfoList field.
func (o *EnterpriseOpenRuleInfo) SetEnterpriseOpenRuleRecordInfoList(v []EnterpriseOpenRuleRecordInfo) {
	o.EnterpriseOpenRuleRecordInfoList = v
}

// GetEnterpriseOpenRuleRelationInfoList returns the EnterpriseOpenRuleRelationInfoList field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseOpenRuleRelationInfoList() []EnterpriseOpenRuleRelationInfo {
	if o == nil || IsNil(o.EnterpriseOpenRuleRelationInfoList) {
		var ret []EnterpriseOpenRuleRelationInfo
		return ret
	}
	return o.EnterpriseOpenRuleRelationInfoList
}

// GetEnterpriseOpenRuleRelationInfoListOk returns a tuple with the EnterpriseOpenRuleRelationInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetEnterpriseOpenRuleRelationInfoListOk() ([]EnterpriseOpenRuleRelationInfo, bool) {
	if o == nil || IsNil(o.EnterpriseOpenRuleRelationInfoList) {
		return nil, false
	}
	return o.EnterpriseOpenRuleRelationInfoList, true
}

// HasEnterpriseOpenRuleRelationInfoList returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasEnterpriseOpenRuleRelationInfoList() bool {
	if o != nil && !IsNil(o.EnterpriseOpenRuleRelationInfoList) {
		return true
	}

	return false
}

// SetEnterpriseOpenRuleRelationInfoList gets a reference to the given []EnterpriseOpenRuleRelationInfo and assigns it to the EnterpriseOpenRuleRelationInfoList field.
func (o *EnterpriseOpenRuleInfo) SetEnterpriseOpenRuleRelationInfoList(v []EnterpriseOpenRuleRelationInfo) {
	o.EnterpriseOpenRuleRelationInfoList = v
}

// GetGmtCreate returns the GmtCreate field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetGmtCreate() string {
	if o == nil || IsNil(o.GmtCreate) {
		var ret string
		return ret
	}
	return *o.GmtCreate
}

// GetGmtCreateOk returns a tuple with the GmtCreate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetGmtCreateOk() (*string, bool) {
	if o == nil || IsNil(o.GmtCreate) {
		return nil, false
	}
	return o.GmtCreate, true
}

// HasGmtCreate returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasGmtCreate() bool {
	if o != nil && !IsNil(o.GmtCreate) {
		return true
	}

	return false
}

// SetGmtCreate gets a reference to the given string and assigns it to the GmtCreate field.
func (o *EnterpriseOpenRuleInfo) SetGmtCreate(v string) {
	o.GmtCreate = &v
}

// GetGmtModified returns the GmtModified field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetGmtModified() string {
	if o == nil || IsNil(o.GmtModified) {
		var ret string
		return ret
	}
	return *o.GmtModified
}

// GetGmtModifiedOk returns a tuple with the GmtModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetGmtModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.GmtModified) {
		return nil, false
	}
	return o.GmtModified, true
}

// HasGmtModified returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasGmtModified() bool {
	if o != nil && !IsNil(o.GmtModified) {
		return true
	}

	return false
}

// SetGmtModified gets a reference to the given string and assigns it to the GmtModified field.
func (o *EnterpriseOpenRuleInfo) SetGmtModified(v string) {
	o.GmtModified = &v
}

// GetInvoiceRuleId returns the InvoiceRuleId field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetInvoiceRuleId() string {
	if o == nil || IsNil(o.InvoiceRuleId) {
		var ret string
		return ret
	}
	return *o.InvoiceRuleId
}

// GetInvoiceRuleIdOk returns a tuple with the InvoiceRuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetInvoiceRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceRuleId) {
		return nil, false
	}
	return o.InvoiceRuleId, true
}

// HasInvoiceRuleId returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasInvoiceRuleId() bool {
	if o != nil && !IsNil(o.InvoiceRuleId) {
		return true
	}

	return false
}

// SetInvoiceRuleId gets a reference to the given string and assigns it to the InvoiceRuleId field.
func (o *EnterpriseOpenRuleInfo) SetInvoiceRuleId(v string) {
	o.InvoiceRuleId = &v
}

// GetInvoiceRuleName returns the InvoiceRuleName field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetInvoiceRuleName() string {
	if o == nil || IsNil(o.InvoiceRuleName) {
		var ret string
		return ret
	}
	return *o.InvoiceRuleName
}

// GetInvoiceRuleNameOk returns a tuple with the InvoiceRuleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetInvoiceRuleNameOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceRuleName) {
		return nil, false
	}
	return o.InvoiceRuleName, true
}

// HasInvoiceRuleName returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasInvoiceRuleName() bool {
	if o != nil && !IsNil(o.InvoiceRuleName) {
		return true
	}

	return false
}

// SetInvoiceRuleName gets a reference to the given string and assigns it to the InvoiceRuleName field.
func (o *EnterpriseOpenRuleInfo) SetInvoiceRuleName(v string) {
	o.InvoiceRuleName = &v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetOwnerId() string {
	if o == nil || IsNil(o.OwnerId) {
		var ret string
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetOwnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given string and assigns it to the OwnerId field.
func (o *EnterpriseOpenRuleInfo) SetOwnerId(v string) {
	o.OwnerId = &v
}

// GetSellerType returns the SellerType field value if set, zero value otherwise.
func (o *EnterpriseOpenRuleInfo) GetSellerType() string {
	if o == nil || IsNil(o.SellerType) {
		var ret string
		return ret
	}
	return *o.SellerType
}

// GetSellerTypeOk returns a tuple with the SellerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnterpriseOpenRuleInfo) GetSellerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SellerType) {
		return nil, false
	}
	return o.SellerType, true
}

// HasSellerType returns a boolean if a field has been set.
func (o *EnterpriseOpenRuleInfo) HasSellerType() bool {
	if o != nil && !IsNil(o.SellerType) {
		return true
	}

	return false
}

// SetSellerType gets a reference to the given string and assigns it to the SellerType field.
func (o *EnterpriseOpenRuleInfo) SetSellerType(v string) {
	o.SellerType = &v
}

func (o EnterpriseOpenRuleInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnterpriseOpenRuleInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EnterpriseId) {
		toSerialize["enterprise_id"] = o.EnterpriseId
	}
	if !IsNil(o.EnterpriseOpenRuleRecordInfoList) {
		toSerialize["enterprise_open_rule_record_info_list"] = o.EnterpriseOpenRuleRecordInfoList
	}
	if !IsNil(o.EnterpriseOpenRuleRelationInfoList) {
		toSerialize["enterprise_open_rule_relation_info_list"] = o.EnterpriseOpenRuleRelationInfoList
	}
	if !IsNil(o.GmtCreate) {
		toSerialize["gmt_create"] = o.GmtCreate
	}
	if !IsNil(o.GmtModified) {
		toSerialize["gmt_modified"] = o.GmtModified
	}
	if !IsNil(o.InvoiceRuleId) {
		toSerialize["invoice_rule_id"] = o.InvoiceRuleId
	}
	if !IsNil(o.InvoiceRuleName) {
		toSerialize["invoice_rule_name"] = o.InvoiceRuleName
	}
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	if !IsNil(o.SellerType) {
		toSerialize["seller_type"] = o.SellerType
	}
	return toSerialize, nil
}

type NullableEnterpriseOpenRuleInfo struct {
	value *EnterpriseOpenRuleInfo
	isSet bool
}

func (v NullableEnterpriseOpenRuleInfo) Get() *EnterpriseOpenRuleInfo {
	return v.value
}

func (v *NullableEnterpriseOpenRuleInfo) Set(val *EnterpriseOpenRuleInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEnterpriseOpenRuleInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEnterpriseOpenRuleInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnterpriseOpenRuleInfo(val *EnterpriseOpenRuleInfo) *NullableEnterpriseOpenRuleInfo {
	return &NullableEnterpriseOpenRuleInfo{value: val, isSet: true}
}

func (v NullableEnterpriseOpenRuleInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnterpriseOpenRuleInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
