/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the AlipayMobilePublicMessageCustomSendModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayMobilePublicMessageCustomSendModel{}

// AlipayMobilePublicMessageCustomSendModel struct for AlipayMobilePublicMessageCustomSendModel
type AlipayMobilePublicMessageCustomSendModel struct {
	// 业务内容，其中包括消息类型msgType、消息体和消息接受人toUserId三大块，在toUserId这一层级新加eventType参数，该字段取值为follow:表示关注事件，click：表示菜单点击事件，enter_ppchat:代表进入事件。具体参见“表1-2 服务窗单发客服消息的biz_content参数说明”。  <a href=\"https://doc.open.alipay.com/doc2/detail.htm?spm=a219a.7386797.0.0.eZqycg&treeId=53&articleId=103448&docType=1\">详情请见</a>
	BizContent *string `json:"biz_content,omitempty"`
}

// NewAlipayMobilePublicMessageCustomSendModel instantiates a new AlipayMobilePublicMessageCustomSendModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayMobilePublicMessageCustomSendModel() *AlipayMobilePublicMessageCustomSendModel {
	this := AlipayMobilePublicMessageCustomSendModel{}
	return &this
}

// NewAlipayMobilePublicMessageCustomSendModelWithDefaults instantiates a new AlipayMobilePublicMessageCustomSendModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayMobilePublicMessageCustomSendModelWithDefaults() *AlipayMobilePublicMessageCustomSendModel {
	this := AlipayMobilePublicMessageCustomSendModel{}
	return &this
}

// GetBizContent returns the BizContent field value if set, zero value otherwise.
func (o *AlipayMobilePublicMessageCustomSendModel) GetBizContent() string {
	if o == nil || IsNil(o.BizContent) {
		var ret string
		return ret
	}
	return *o.BizContent
}

// GetBizContentOk returns a tuple with the BizContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayMobilePublicMessageCustomSendModel) GetBizContentOk() (*string, bool) {
	if o == nil || IsNil(o.BizContent) {
		return nil, false
	}
	return o.BizContent, true
}

// HasBizContent returns a boolean if a field has been set.
func (o *AlipayMobilePublicMessageCustomSendModel) HasBizContent() bool {
	if o != nil && !IsNil(o.BizContent) {
		return true
	}

	return false
}

// SetBizContent gets a reference to the given string and assigns it to the BizContent field.
func (o *AlipayMobilePublicMessageCustomSendModel) SetBizContent(v string) {
	o.BizContent = &v
}

func (o AlipayMobilePublicMessageCustomSendModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayMobilePublicMessageCustomSendModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BizContent) {
		toSerialize["biz_content"] = o.BizContent
	}
	return toSerialize, nil
}

type NullableAlipayMobilePublicMessageCustomSendModel struct {
	value *AlipayMobilePublicMessageCustomSendModel
	isSet bool
}

func (v NullableAlipayMobilePublicMessageCustomSendModel) Get() *AlipayMobilePublicMessageCustomSendModel {
	return v.value
}

func (v *NullableAlipayMobilePublicMessageCustomSendModel) Set(val *AlipayMobilePublicMessageCustomSendModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayMobilePublicMessageCustomSendModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayMobilePublicMessageCustomSendModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayMobilePublicMessageCustomSendModel(val *AlipayMobilePublicMessageCustomSendModel) *NullableAlipayMobilePublicMessageCustomSendModel {
	return &NullableAlipayMobilePublicMessageCustomSendModel{value: val, isSet: true}
}

func (v NullableAlipayMobilePublicMessageCustomSendModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayMobilePublicMessageCustomSendModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
