/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AlipayTradeFastpayRefundQueryResponseModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayTradeFastpayRefundQueryResponseModel{}

// AlipayTradeFastpayRefundQueryResponseModel struct for AlipayTradeFastpayRefundQueryResponseModel
type AlipayTradeFastpayRefundQueryResponseModel struct {
	DepositBackInfo *DepositBackInfo `json:"deposit_back_info,omitempty"`
	// 银行卡冲退信息列表。 默认不返回该信息，需要在入参的query_options中指定\"deposit_back_info_list\"值时才返回该字段信息。
	DepositBackInfoList []DepositBackInfo `json:"deposit_back_info_list,omitempty"`
	EnterprisePayInfo *EnterprisePayInfo `json:"enterprise_pay_info,omitempty"`
	// 退款失败错误码。只在使用异步退款接口情况下才会返回该字段
	ErrorCode *string `json:"error_code,omitempty"`
	// 退款时间。默认不返回该信息，需要在入参的query_options中指定\"gmt_refund_pay\"值时才返回该字段信息。
	GmtRefundPay *string `json:"gmt_refund_pay,omitempty"`
	// 行业特殊信息（例如在医保卡支付退款中，医保局向商户返回医疗信息）。
	IndustrySepcDetail *string `json:"industry_sepc_detail,omitempty"`
	// 本笔退款对应的退款请求号
	OutRequestNo *string `json:"out_request_no,omitempty"`
	// 创建交易传入的商户订单号
	OutTradeNo *string `json:"out_trade_no,omitempty"`
	// 本次退款金额中买家退款金额。单位：元。 该字段默认不返回；
	PresentRefundBuyerAmount *string `json:"present_refund_buyer_amount,omitempty"`
	// 本次退款金额中平台优惠退款金额。单位：元。 该字段默认不返回；
	PresentRefundDiscountAmount *string `json:"present_refund_discount_amount,omitempty"`
	// 本次退款金额中商家优惠退款金额。单位：元。 该字段默认不返回；
	PresentRefundMdiscountAmount *string `json:"present_refund_mdiscount_amount,omitempty"`
	// 本次退款请求，对应的退款金额。单位：元。
	RefundAmount *string `json:"refund_amount,omitempty"`
	// 若支付渠道包含医保统筹、个账，则显示退款的渠道信息。如统筹OUTSIDEGOVCARD，个账OUTSIDEACCCARD
	RefundChannelList *string `json:"refund_channel_list,omitempty"`
	// 若支付渠道包含医保统筹、个账，全渠道退款成功时返回SUCCESS，全失败时返回FAIL，部分成功时返回PART_SUCCESS
	RefundChannelStatus *string `json:"refund_channel_status,omitempty"`
	// 本次退款针对收款方的退收费金额；单位：元。 只在机构间联模式下返回，其它场景下不返回该字段；
	RefundChargeAmount *string `json:"refund_charge_amount,omitempty"`
	// 退费信息
	RefundChargeInfoList []RefundChargeInfo `json:"refund_charge_info_list,omitempty"`
	// 本次退款使用的资金渠道； 默认不返回该信息，需要在入参的query_options中指定\"refund_detail_item_list\"值时才返回该字段信息。
	RefundDetailItemList []TradeFundBill `json:"refund_detail_item_list,omitempty"`
	// 本次退款金额中退惠营宝的金额。单位：元。
	RefundHybAmount *string `json:"refund_hyb_amount,omitempty"`
	// 发起退款时，传入的退款原因
	RefundReason *string `json:"refund_reason,omitempty"`
	// 退分账明细信息，当前仅在直付通产品中返回。
	RefundRoyaltys []RefundRoyaltyResult `json:"refund_royaltys,omitempty"`
	// 退款清算编号，用于清算对账使用； 只在机构间联模式下返回，其它场景下不返回该字段；
	RefundSettlementId *string `json:"refund_settlement_id,omitempty"`
	// 退款状态。枚举值： REFUND_SUCCESS 退款处理成功； 未返回该字段表示退款请求未收到或者退款失败； 注：如果退款查询发起时间早于退款时间，或者间隔退款发起时间太短，可能出现退款查询时还没处理成功，后面又处理成功的情况，建议商户在退款发起后间隔10秒以上再发起退款查询请求。
	RefundStatus *string `json:"refund_status,omitempty"`
	// 本交易支付时使用的所有优惠券信息。 只有在query_options中指定refund_voucher_detail_list时才返回该字段信息。
	RefundVoucherDetailList []VoucherDetail `json:"refund_voucher_detail_list,omitempty"`
	// 本次商户实际退回金额；单位：元。 默认不返回该信息，需要在入参的query_options中指定\"refund_detail_item_list\"值时才返回该字段信息。
	SendBackFee *string `json:"send_back_fee,omitempty"`
	// 该笔退款所对应的交易的订单金额。单位：元。
	TotalAmount *string `json:"total_amount,omitempty"`
	// 支付宝交易号
	TradeNo *string `json:"trade_no,omitempty"`
}

// NewAlipayTradeFastpayRefundQueryResponseModel instantiates a new AlipayTradeFastpayRefundQueryResponseModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayTradeFastpayRefundQueryResponseModel() *AlipayTradeFastpayRefundQueryResponseModel {
	this := AlipayTradeFastpayRefundQueryResponseModel{}
	return &this
}

// NewAlipayTradeFastpayRefundQueryResponseModelWithDefaults instantiates a new AlipayTradeFastpayRefundQueryResponseModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayTradeFastpayRefundQueryResponseModelWithDefaults() *AlipayTradeFastpayRefundQueryResponseModel {
	this := AlipayTradeFastpayRefundQueryResponseModel{}
	return &this
}

// GetDepositBackInfo returns the DepositBackInfo field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetDepositBackInfo() DepositBackInfo {
	if o == nil || IsNil(o.DepositBackInfo) {
		var ret DepositBackInfo
		return ret
	}
	return *o.DepositBackInfo
}

// GetDepositBackInfoOk returns a tuple with the DepositBackInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetDepositBackInfoOk() (*DepositBackInfo, bool) {
	if o == nil || IsNil(o.DepositBackInfo) {
		return nil, false
	}
	return o.DepositBackInfo, true
}

// HasDepositBackInfo returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasDepositBackInfo() bool {
	if o != nil && !IsNil(o.DepositBackInfo) {
		return true
	}

	return false
}

// SetDepositBackInfo gets a reference to the given DepositBackInfo and assigns it to the DepositBackInfo field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetDepositBackInfo(v DepositBackInfo) {
	o.DepositBackInfo = &v
}

// GetDepositBackInfoList returns the DepositBackInfoList field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetDepositBackInfoList() []DepositBackInfo {
	if o == nil || IsNil(o.DepositBackInfoList) {
		var ret []DepositBackInfo
		return ret
	}
	return o.DepositBackInfoList
}

// GetDepositBackInfoListOk returns a tuple with the DepositBackInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetDepositBackInfoListOk() ([]DepositBackInfo, bool) {
	if o == nil || IsNil(o.DepositBackInfoList) {
		return nil, false
	}
	return o.DepositBackInfoList, true
}

// HasDepositBackInfoList returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasDepositBackInfoList() bool {
	if o != nil && !IsNil(o.DepositBackInfoList) {
		return true
	}

	return false
}

// SetDepositBackInfoList gets a reference to the given []DepositBackInfo and assigns it to the DepositBackInfoList field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetDepositBackInfoList(v []DepositBackInfo) {
	o.DepositBackInfoList = v
}

// GetEnterprisePayInfo returns the EnterprisePayInfo field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetEnterprisePayInfo() EnterprisePayInfo {
	if o == nil || IsNil(o.EnterprisePayInfo) {
		var ret EnterprisePayInfo
		return ret
	}
	return *o.EnterprisePayInfo
}

// GetEnterprisePayInfoOk returns a tuple with the EnterprisePayInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetEnterprisePayInfoOk() (*EnterprisePayInfo, bool) {
	if o == nil || IsNil(o.EnterprisePayInfo) {
		return nil, false
	}
	return o.EnterprisePayInfo, true
}

// HasEnterprisePayInfo returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasEnterprisePayInfo() bool {
	if o != nil && !IsNil(o.EnterprisePayInfo) {
		return true
	}

	return false
}

// SetEnterprisePayInfo gets a reference to the given EnterprisePayInfo and assigns it to the EnterprisePayInfo field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetEnterprisePayInfo(v EnterprisePayInfo) {
	o.EnterprisePayInfo = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetGmtRefundPay returns the GmtRefundPay field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetGmtRefundPay() string {
	if o == nil || IsNil(o.GmtRefundPay) {
		var ret string
		return ret
	}
	return *o.GmtRefundPay
}

// GetGmtRefundPayOk returns a tuple with the GmtRefundPay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetGmtRefundPayOk() (*string, bool) {
	if o == nil || IsNil(o.GmtRefundPay) {
		return nil, false
	}
	return o.GmtRefundPay, true
}

// HasGmtRefundPay returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasGmtRefundPay() bool {
	if o != nil && !IsNil(o.GmtRefundPay) {
		return true
	}

	return false
}

// SetGmtRefundPay gets a reference to the given string and assigns it to the GmtRefundPay field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetGmtRefundPay(v string) {
	o.GmtRefundPay = &v
}

// GetIndustrySepcDetail returns the IndustrySepcDetail field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetIndustrySepcDetail() string {
	if o == nil || IsNil(o.IndustrySepcDetail) {
		var ret string
		return ret
	}
	return *o.IndustrySepcDetail
}

// GetIndustrySepcDetailOk returns a tuple with the IndustrySepcDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetIndustrySepcDetailOk() (*string, bool) {
	if o == nil || IsNil(o.IndustrySepcDetail) {
		return nil, false
	}
	return o.IndustrySepcDetail, true
}

// HasIndustrySepcDetail returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasIndustrySepcDetail() bool {
	if o != nil && !IsNil(o.IndustrySepcDetail) {
		return true
	}

	return false
}

// SetIndustrySepcDetail gets a reference to the given string and assigns it to the IndustrySepcDetail field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetIndustrySepcDetail(v string) {
	o.IndustrySepcDetail = &v
}

// GetOutRequestNo returns the OutRequestNo field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetOutRequestNo() string {
	if o == nil || IsNil(o.OutRequestNo) {
		var ret string
		return ret
	}
	return *o.OutRequestNo
}

// GetOutRequestNoOk returns a tuple with the OutRequestNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetOutRequestNoOk() (*string, bool) {
	if o == nil || IsNil(o.OutRequestNo) {
		return nil, false
	}
	return o.OutRequestNo, true
}

// HasOutRequestNo returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasOutRequestNo() bool {
	if o != nil && !IsNil(o.OutRequestNo) {
		return true
	}

	return false
}

// SetOutRequestNo gets a reference to the given string and assigns it to the OutRequestNo field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetOutRequestNo(v string) {
	o.OutRequestNo = &v
}

// GetOutTradeNo returns the OutTradeNo field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetOutTradeNo() string {
	if o == nil || IsNil(o.OutTradeNo) {
		var ret string
		return ret
	}
	return *o.OutTradeNo
}

// GetOutTradeNoOk returns a tuple with the OutTradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetOutTradeNoOk() (*string, bool) {
	if o == nil || IsNil(o.OutTradeNo) {
		return nil, false
	}
	return o.OutTradeNo, true
}

// HasOutTradeNo returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasOutTradeNo() bool {
	if o != nil && !IsNil(o.OutTradeNo) {
		return true
	}

	return false
}

// SetOutTradeNo gets a reference to the given string and assigns it to the OutTradeNo field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetOutTradeNo(v string) {
	o.OutTradeNo = &v
}

// GetPresentRefundBuyerAmount returns the PresentRefundBuyerAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundBuyerAmount() string {
	if o == nil || IsNil(o.PresentRefundBuyerAmount) {
		var ret string
		return ret
	}
	return *o.PresentRefundBuyerAmount
}

// GetPresentRefundBuyerAmountOk returns a tuple with the PresentRefundBuyerAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundBuyerAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PresentRefundBuyerAmount) {
		return nil, false
	}
	return o.PresentRefundBuyerAmount, true
}

// HasPresentRefundBuyerAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasPresentRefundBuyerAmount() bool {
	if o != nil && !IsNil(o.PresentRefundBuyerAmount) {
		return true
	}

	return false
}

// SetPresentRefundBuyerAmount gets a reference to the given string and assigns it to the PresentRefundBuyerAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetPresentRefundBuyerAmount(v string) {
	o.PresentRefundBuyerAmount = &v
}

// GetPresentRefundDiscountAmount returns the PresentRefundDiscountAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundDiscountAmount() string {
	if o == nil || IsNil(o.PresentRefundDiscountAmount) {
		var ret string
		return ret
	}
	return *o.PresentRefundDiscountAmount
}

// GetPresentRefundDiscountAmountOk returns a tuple with the PresentRefundDiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundDiscountAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PresentRefundDiscountAmount) {
		return nil, false
	}
	return o.PresentRefundDiscountAmount, true
}

// HasPresentRefundDiscountAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasPresentRefundDiscountAmount() bool {
	if o != nil && !IsNil(o.PresentRefundDiscountAmount) {
		return true
	}

	return false
}

// SetPresentRefundDiscountAmount gets a reference to the given string and assigns it to the PresentRefundDiscountAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetPresentRefundDiscountAmount(v string) {
	o.PresentRefundDiscountAmount = &v
}

// GetPresentRefundMdiscountAmount returns the PresentRefundMdiscountAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundMdiscountAmount() string {
	if o == nil || IsNil(o.PresentRefundMdiscountAmount) {
		var ret string
		return ret
	}
	return *o.PresentRefundMdiscountAmount
}

// GetPresentRefundMdiscountAmountOk returns a tuple with the PresentRefundMdiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetPresentRefundMdiscountAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PresentRefundMdiscountAmount) {
		return nil, false
	}
	return o.PresentRefundMdiscountAmount, true
}

// HasPresentRefundMdiscountAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasPresentRefundMdiscountAmount() bool {
	if o != nil && !IsNil(o.PresentRefundMdiscountAmount) {
		return true
	}

	return false
}

// SetPresentRefundMdiscountAmount gets a reference to the given string and assigns it to the PresentRefundMdiscountAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetPresentRefundMdiscountAmount(v string) {
	o.PresentRefundMdiscountAmount = &v
}

// GetRefundAmount returns the RefundAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundAmount() string {
	if o == nil || IsNil(o.RefundAmount) {
		var ret string
		return ret
	}
	return *o.RefundAmount
}

// GetRefundAmountOk returns a tuple with the RefundAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundAmountOk() (*string, bool) {
	if o == nil || IsNil(o.RefundAmount) {
		return nil, false
	}
	return o.RefundAmount, true
}

// HasRefundAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundAmount() bool {
	if o != nil && !IsNil(o.RefundAmount) {
		return true
	}

	return false
}

// SetRefundAmount gets a reference to the given string and assigns it to the RefundAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundAmount(v string) {
	o.RefundAmount = &v
}

// GetRefundChannelList returns the RefundChannelList field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChannelList() string {
	if o == nil || IsNil(o.RefundChannelList) {
		var ret string
		return ret
	}
	return *o.RefundChannelList
}

// GetRefundChannelListOk returns a tuple with the RefundChannelList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChannelListOk() (*string, bool) {
	if o == nil || IsNil(o.RefundChannelList) {
		return nil, false
	}
	return o.RefundChannelList, true
}

// HasRefundChannelList returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundChannelList() bool {
	if o != nil && !IsNil(o.RefundChannelList) {
		return true
	}

	return false
}

// SetRefundChannelList gets a reference to the given string and assigns it to the RefundChannelList field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundChannelList(v string) {
	o.RefundChannelList = &v
}

// GetRefundChannelStatus returns the RefundChannelStatus field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChannelStatus() string {
	if o == nil || IsNil(o.RefundChannelStatus) {
		var ret string
		return ret
	}
	return *o.RefundChannelStatus
}

// GetRefundChannelStatusOk returns a tuple with the RefundChannelStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChannelStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RefundChannelStatus) {
		return nil, false
	}
	return o.RefundChannelStatus, true
}

// HasRefundChannelStatus returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundChannelStatus() bool {
	if o != nil && !IsNil(o.RefundChannelStatus) {
		return true
	}

	return false
}

// SetRefundChannelStatus gets a reference to the given string and assigns it to the RefundChannelStatus field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundChannelStatus(v string) {
	o.RefundChannelStatus = &v
}

// GetRefundChargeAmount returns the RefundChargeAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChargeAmount() string {
	if o == nil || IsNil(o.RefundChargeAmount) {
		var ret string
		return ret
	}
	return *o.RefundChargeAmount
}

// GetRefundChargeAmountOk returns a tuple with the RefundChargeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChargeAmountOk() (*string, bool) {
	if o == nil || IsNil(o.RefundChargeAmount) {
		return nil, false
	}
	return o.RefundChargeAmount, true
}

// HasRefundChargeAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundChargeAmount() bool {
	if o != nil && !IsNil(o.RefundChargeAmount) {
		return true
	}

	return false
}

// SetRefundChargeAmount gets a reference to the given string and assigns it to the RefundChargeAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundChargeAmount(v string) {
	o.RefundChargeAmount = &v
}

// GetRefundChargeInfoList returns the RefundChargeInfoList field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChargeInfoList() []RefundChargeInfo {
	if o == nil || IsNil(o.RefundChargeInfoList) {
		var ret []RefundChargeInfo
		return ret
	}
	return o.RefundChargeInfoList
}

// GetRefundChargeInfoListOk returns a tuple with the RefundChargeInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundChargeInfoListOk() ([]RefundChargeInfo, bool) {
	if o == nil || IsNil(o.RefundChargeInfoList) {
		return nil, false
	}
	return o.RefundChargeInfoList, true
}

// HasRefundChargeInfoList returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundChargeInfoList() bool {
	if o != nil && !IsNil(o.RefundChargeInfoList) {
		return true
	}

	return false
}

// SetRefundChargeInfoList gets a reference to the given []RefundChargeInfo and assigns it to the RefundChargeInfoList field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundChargeInfoList(v []RefundChargeInfo) {
	o.RefundChargeInfoList = v
}

// GetRefundDetailItemList returns the RefundDetailItemList field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundDetailItemList() []TradeFundBill {
	if o == nil || IsNil(o.RefundDetailItemList) {
		var ret []TradeFundBill
		return ret
	}
	return o.RefundDetailItemList
}

// GetRefundDetailItemListOk returns a tuple with the RefundDetailItemList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundDetailItemListOk() ([]TradeFundBill, bool) {
	if o == nil || IsNil(o.RefundDetailItemList) {
		return nil, false
	}
	return o.RefundDetailItemList, true
}

// HasRefundDetailItemList returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundDetailItemList() bool {
	if o != nil && !IsNil(o.RefundDetailItemList) {
		return true
	}

	return false
}

// SetRefundDetailItemList gets a reference to the given []TradeFundBill and assigns it to the RefundDetailItemList field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundDetailItemList(v []TradeFundBill) {
	o.RefundDetailItemList = v
}

// GetRefundHybAmount returns the RefundHybAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundHybAmount() string {
	if o == nil || IsNil(o.RefundHybAmount) {
		var ret string
		return ret
	}
	return *o.RefundHybAmount
}

// GetRefundHybAmountOk returns a tuple with the RefundHybAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundHybAmountOk() (*string, bool) {
	if o == nil || IsNil(o.RefundHybAmount) {
		return nil, false
	}
	return o.RefundHybAmount, true
}

// HasRefundHybAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundHybAmount() bool {
	if o != nil && !IsNil(o.RefundHybAmount) {
		return true
	}

	return false
}

// SetRefundHybAmount gets a reference to the given string and assigns it to the RefundHybAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundHybAmount(v string) {
	o.RefundHybAmount = &v
}

// GetRefundReason returns the RefundReason field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundReason() string {
	if o == nil || IsNil(o.RefundReason) {
		var ret string
		return ret
	}
	return *o.RefundReason
}

// GetRefundReasonOk returns a tuple with the RefundReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RefundReason) {
		return nil, false
	}
	return o.RefundReason, true
}

// HasRefundReason returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundReason() bool {
	if o != nil && !IsNil(o.RefundReason) {
		return true
	}

	return false
}

// SetRefundReason gets a reference to the given string and assigns it to the RefundReason field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundReason(v string) {
	o.RefundReason = &v
}

// GetRefundRoyaltys returns the RefundRoyaltys field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundRoyaltys() []RefundRoyaltyResult {
	if o == nil || IsNil(o.RefundRoyaltys) {
		var ret []RefundRoyaltyResult
		return ret
	}
	return o.RefundRoyaltys
}

// GetRefundRoyaltysOk returns a tuple with the RefundRoyaltys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundRoyaltysOk() ([]RefundRoyaltyResult, bool) {
	if o == nil || IsNil(o.RefundRoyaltys) {
		return nil, false
	}
	return o.RefundRoyaltys, true
}

// HasRefundRoyaltys returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundRoyaltys() bool {
	if o != nil && !IsNil(o.RefundRoyaltys) {
		return true
	}

	return false
}

// SetRefundRoyaltys gets a reference to the given []RefundRoyaltyResult and assigns it to the RefundRoyaltys field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundRoyaltys(v []RefundRoyaltyResult) {
	o.RefundRoyaltys = v
}

// GetRefundSettlementId returns the RefundSettlementId field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundSettlementId() string {
	if o == nil || IsNil(o.RefundSettlementId) {
		var ret string
		return ret
	}
	return *o.RefundSettlementId
}

// GetRefundSettlementIdOk returns a tuple with the RefundSettlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundSettlementIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefundSettlementId) {
		return nil, false
	}
	return o.RefundSettlementId, true
}

// HasRefundSettlementId returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundSettlementId() bool {
	if o != nil && !IsNil(o.RefundSettlementId) {
		return true
	}

	return false
}

// SetRefundSettlementId gets a reference to the given string and assigns it to the RefundSettlementId field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundSettlementId(v string) {
	o.RefundSettlementId = &v
}

// GetRefundStatus returns the RefundStatus field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundStatus() string {
	if o == nil || IsNil(o.RefundStatus) {
		var ret string
		return ret
	}
	return *o.RefundStatus
}

// GetRefundStatusOk returns a tuple with the RefundStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RefundStatus) {
		return nil, false
	}
	return o.RefundStatus, true
}

// HasRefundStatus returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundStatus() bool {
	if o != nil && !IsNil(o.RefundStatus) {
		return true
	}

	return false
}

// SetRefundStatus gets a reference to the given string and assigns it to the RefundStatus field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundStatus(v string) {
	o.RefundStatus = &v
}

// GetRefundVoucherDetailList returns the RefundVoucherDetailList field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundVoucherDetailList() []VoucherDetail {
	if o == nil || IsNil(o.RefundVoucherDetailList) {
		var ret []VoucherDetail
		return ret
	}
	return o.RefundVoucherDetailList
}

// GetRefundVoucherDetailListOk returns a tuple with the RefundVoucherDetailList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetRefundVoucherDetailListOk() ([]VoucherDetail, bool) {
	if o == nil || IsNil(o.RefundVoucherDetailList) {
		return nil, false
	}
	return o.RefundVoucherDetailList, true
}

// HasRefundVoucherDetailList returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasRefundVoucherDetailList() bool {
	if o != nil && !IsNil(o.RefundVoucherDetailList) {
		return true
	}

	return false
}

// SetRefundVoucherDetailList gets a reference to the given []VoucherDetail and assigns it to the RefundVoucherDetailList field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetRefundVoucherDetailList(v []VoucherDetail) {
	o.RefundVoucherDetailList = v
}

// GetSendBackFee returns the SendBackFee field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetSendBackFee() string {
	if o == nil || IsNil(o.SendBackFee) {
		var ret string
		return ret
	}
	return *o.SendBackFee
}

// GetSendBackFeeOk returns a tuple with the SendBackFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetSendBackFeeOk() (*string, bool) {
	if o == nil || IsNil(o.SendBackFee) {
		return nil, false
	}
	return o.SendBackFee, true
}

// HasSendBackFee returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasSendBackFee() bool {
	if o != nil && !IsNil(o.SendBackFee) {
		return true
	}

	return false
}

// SetSendBackFee gets a reference to the given string and assigns it to the SendBackFee field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetSendBackFee(v string) {
	o.SendBackFee = &v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetTotalAmount() string {
	if o == nil || IsNil(o.TotalAmount) {
		var ret string
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetTotalAmountOk() (*string, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given string and assigns it to the TotalAmount field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetTotalAmount(v string) {
	o.TotalAmount = &v
}

// GetTradeNo returns the TradeNo field value if set, zero value otherwise.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetTradeNo() string {
	if o == nil || IsNil(o.TradeNo) {
		var ret string
		return ret
	}
	return *o.TradeNo
}

// GetTradeNoOk returns a tuple with the TradeNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) GetTradeNoOk() (*string, bool) {
	if o == nil || IsNil(o.TradeNo) {
		return nil, false
	}
	return o.TradeNo, true
}

// HasTradeNo returns a boolean if a field has been set.
func (o *AlipayTradeFastpayRefundQueryResponseModel) HasTradeNo() bool {
	if o != nil && !IsNil(o.TradeNo) {
		return true
	}

	return false
}

// SetTradeNo gets a reference to the given string and assigns it to the TradeNo field.
func (o *AlipayTradeFastpayRefundQueryResponseModel) SetTradeNo(v string) {
	o.TradeNo = &v
}

func (o AlipayTradeFastpayRefundQueryResponseModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayTradeFastpayRefundQueryResponseModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DepositBackInfo) {
		toSerialize["deposit_back_info"] = o.DepositBackInfo
	}
	if !IsNil(o.DepositBackInfoList) {
		toSerialize["deposit_back_info_list"] = o.DepositBackInfoList
	}
	if !IsNil(o.EnterprisePayInfo) {
		toSerialize["enterprise_pay_info"] = o.EnterprisePayInfo
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["error_code"] = o.ErrorCode
	}
	if !IsNil(o.GmtRefundPay) {
		toSerialize["gmt_refund_pay"] = o.GmtRefundPay
	}
	if !IsNil(o.IndustrySepcDetail) {
		toSerialize["industry_sepc_detail"] = o.IndustrySepcDetail
	}
	if !IsNil(o.OutRequestNo) {
		toSerialize["out_request_no"] = o.OutRequestNo
	}
	if !IsNil(o.OutTradeNo) {
		toSerialize["out_trade_no"] = o.OutTradeNo
	}
	if !IsNil(o.PresentRefundBuyerAmount) {
		toSerialize["present_refund_buyer_amount"] = o.PresentRefundBuyerAmount
	}
	if !IsNil(o.PresentRefundDiscountAmount) {
		toSerialize["present_refund_discount_amount"] = o.PresentRefundDiscountAmount
	}
	if !IsNil(o.PresentRefundMdiscountAmount) {
		toSerialize["present_refund_mdiscount_amount"] = o.PresentRefundMdiscountAmount
	}
	if !IsNil(o.RefundAmount) {
		toSerialize["refund_amount"] = o.RefundAmount
	}
	if !IsNil(o.RefundChannelList) {
		toSerialize["refund_channel_list"] = o.RefundChannelList
	}
	if !IsNil(o.RefundChannelStatus) {
		toSerialize["refund_channel_status"] = o.RefundChannelStatus
	}
	if !IsNil(o.RefundChargeAmount) {
		toSerialize["refund_charge_amount"] = o.RefundChargeAmount
	}
	if !IsNil(o.RefundChargeInfoList) {
		toSerialize["refund_charge_info_list"] = o.RefundChargeInfoList
	}
	if !IsNil(o.RefundDetailItemList) {
		toSerialize["refund_detail_item_list"] = o.RefundDetailItemList
	}
	if !IsNil(o.RefundHybAmount) {
		toSerialize["refund_hyb_amount"] = o.RefundHybAmount
	}
	if !IsNil(o.RefundReason) {
		toSerialize["refund_reason"] = o.RefundReason
	}
	if !IsNil(o.RefundRoyaltys) {
		toSerialize["refund_royaltys"] = o.RefundRoyaltys
	}
	if !IsNil(o.RefundSettlementId) {
		toSerialize["refund_settlement_id"] = o.RefundSettlementId
	}
	if !IsNil(o.RefundStatus) {
		toSerialize["refund_status"] = o.RefundStatus
	}
	if !IsNil(o.RefundVoucherDetailList) {
		toSerialize["refund_voucher_detail_list"] = o.RefundVoucherDetailList
	}
	if !IsNil(o.SendBackFee) {
		toSerialize["send_back_fee"] = o.SendBackFee
	}
	if !IsNil(o.TotalAmount) {
		toSerialize["total_amount"] = o.TotalAmount
	}
	if !IsNil(o.TradeNo) {
		toSerialize["trade_no"] = o.TradeNo
	}
	return toSerialize, nil
}

type NullableAlipayTradeFastpayRefundQueryResponseModel struct {
	value *AlipayTradeFastpayRefundQueryResponseModel
	isSet bool
}

func (v NullableAlipayTradeFastpayRefundQueryResponseModel) Get() *AlipayTradeFastpayRefundQueryResponseModel {
	return v.value
}

func (v *NullableAlipayTradeFastpayRefundQueryResponseModel) Set(val *AlipayTradeFastpayRefundQueryResponseModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayTradeFastpayRefundQueryResponseModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayTradeFastpayRefundQueryResponseModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayTradeFastpayRefundQueryResponseModel(val *AlipayTradeFastpayRefundQueryResponseModel) *NullableAlipayTradeFastpayRefundQueryResponseModel {
	return &NullableAlipayTradeFastpayRefundQueryResponseModel{value: val, isSet: true}
}

func (v NullableAlipayTradeFastpayRefundQueryResponseModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayTradeFastpayRefundQueryResponseModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


