/*
支付宝开放平台API

支付宝开放平台v3协议文档

API version: 2024-07-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alipay

import (
	"encoding/json"
)

// checks if the AlipayFundAccountbookCreateModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlipayFundAccountbookCreateModel{}

// AlipayFundAccountbookCreateModel struct for AlipayFundAccountbookCreateModel
type AlipayFundAccountbookCreateModel struct {
	// JSON格式，传递业务扩展参数
	ExtInfo *string `json:"ext_info,omitempty"`
	// 外部商户系统会员的唯一标识，自定义传入
	MerchantUserId *string `json:"merchant_user_id,omitempty"`
	// 外部商户用户类型:BUSINESS_EMPLOYEE
	MerchantUserType *string `json:"merchant_user_type,omitempty"`
	// 资金记账本的业务场景
	SceneCode *string `json:"scene_code,omitempty"`
}

// NewAlipayFundAccountbookCreateModel instantiates a new AlipayFundAccountbookCreateModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlipayFundAccountbookCreateModel() *AlipayFundAccountbookCreateModel {
	this := AlipayFundAccountbookCreateModel{}
	return &this
}

// NewAlipayFundAccountbookCreateModelWithDefaults instantiates a new AlipayFundAccountbookCreateModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlipayFundAccountbookCreateModelWithDefaults() *AlipayFundAccountbookCreateModel {
	this := AlipayFundAccountbookCreateModel{}
	return &this
}

// GetExtInfo returns the ExtInfo field value if set, zero value otherwise.
func (o *AlipayFundAccountbookCreateModel) GetExtInfo() string {
	if o == nil || IsNil(o.ExtInfo) {
		var ret string
		return ret
	}
	return *o.ExtInfo
}

// GetExtInfoOk returns a tuple with the ExtInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayFundAccountbookCreateModel) GetExtInfoOk() (*string, bool) {
	if o == nil || IsNil(o.ExtInfo) {
		return nil, false
	}
	return o.ExtInfo, true
}

// HasExtInfo returns a boolean if a field has been set.
func (o *AlipayFundAccountbookCreateModel) HasExtInfo() bool {
	if o != nil && !IsNil(o.ExtInfo) {
		return true
	}

	return false
}

// SetExtInfo gets a reference to the given string and assigns it to the ExtInfo field.
func (o *AlipayFundAccountbookCreateModel) SetExtInfo(v string) {
	o.ExtInfo = &v
}

// GetMerchantUserId returns the MerchantUserId field value if set, zero value otherwise.
func (o *AlipayFundAccountbookCreateModel) GetMerchantUserId() string {
	if o == nil || IsNil(o.MerchantUserId) {
		var ret string
		return ret
	}
	return *o.MerchantUserId
}

// GetMerchantUserIdOk returns a tuple with the MerchantUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayFundAccountbookCreateModel) GetMerchantUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantUserId) {
		return nil, false
	}
	return o.MerchantUserId, true
}

// HasMerchantUserId returns a boolean if a field has been set.
func (o *AlipayFundAccountbookCreateModel) HasMerchantUserId() bool {
	if o != nil && !IsNil(o.MerchantUserId) {
		return true
	}

	return false
}

// SetMerchantUserId gets a reference to the given string and assigns it to the MerchantUserId field.
func (o *AlipayFundAccountbookCreateModel) SetMerchantUserId(v string) {
	o.MerchantUserId = &v
}

// GetMerchantUserType returns the MerchantUserType field value if set, zero value otherwise.
func (o *AlipayFundAccountbookCreateModel) GetMerchantUserType() string {
	if o == nil || IsNil(o.MerchantUserType) {
		var ret string
		return ret
	}
	return *o.MerchantUserType
}

// GetMerchantUserTypeOk returns a tuple with the MerchantUserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayFundAccountbookCreateModel) GetMerchantUserTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantUserType) {
		return nil, false
	}
	return o.MerchantUserType, true
}

// HasMerchantUserType returns a boolean if a field has been set.
func (o *AlipayFundAccountbookCreateModel) HasMerchantUserType() bool {
	if o != nil && !IsNil(o.MerchantUserType) {
		return true
	}

	return false
}

// SetMerchantUserType gets a reference to the given string and assigns it to the MerchantUserType field.
func (o *AlipayFundAccountbookCreateModel) SetMerchantUserType(v string) {
	o.MerchantUserType = &v
}

// GetSceneCode returns the SceneCode field value if set, zero value otherwise.
func (o *AlipayFundAccountbookCreateModel) GetSceneCode() string {
	if o == nil || IsNil(o.SceneCode) {
		var ret string
		return ret
	}
	return *o.SceneCode
}

// GetSceneCodeOk returns a tuple with the SceneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlipayFundAccountbookCreateModel) GetSceneCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SceneCode) {
		return nil, false
	}
	return o.SceneCode, true
}

// HasSceneCode returns a boolean if a field has been set.
func (o *AlipayFundAccountbookCreateModel) HasSceneCode() bool {
	if o != nil && !IsNil(o.SceneCode) {
		return true
	}

	return false
}

// SetSceneCode gets a reference to the given string and assigns it to the SceneCode field.
func (o *AlipayFundAccountbookCreateModel) SetSceneCode(v string) {
	o.SceneCode = &v
}

func (o AlipayFundAccountbookCreateModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlipayFundAccountbookCreateModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExtInfo) {
		toSerialize["ext_info"] = o.ExtInfo
	}
	if !IsNil(o.MerchantUserId) {
		toSerialize["merchant_user_id"] = o.MerchantUserId
	}
	if !IsNil(o.MerchantUserType) {
		toSerialize["merchant_user_type"] = o.MerchantUserType
	}
	if !IsNil(o.SceneCode) {
		toSerialize["scene_code"] = o.SceneCode
	}
	return toSerialize, nil
}

type NullableAlipayFundAccountbookCreateModel struct {
	value *AlipayFundAccountbookCreateModel
	isSet bool
}

func (v NullableAlipayFundAccountbookCreateModel) Get() *AlipayFundAccountbookCreateModel {
	return v.value
}

func (v *NullableAlipayFundAccountbookCreateModel) Set(val *AlipayFundAccountbookCreateModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAlipayFundAccountbookCreateModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAlipayFundAccountbookCreateModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlipayFundAccountbookCreateModel(val *AlipayFundAccountbookCreateModel) *NullableAlipayFundAccountbookCreateModel {
	return &NullableAlipayFundAccountbookCreateModel{value: val, isSet: true}
}

func (v NullableAlipayFundAccountbookCreateModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlipayFundAccountbookCreateModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
